### ISSUE TITLE
 [mysql flavor] .onDupUpdate() with addition or other "calculating" parameters

### ISSUE THREAD

**Issue by ronny332** [hiddentao/squel#100]
Hello,

since v2.5 .onDupUpdate() is a very nice function for the mysql flavor, but how can I use it for instance together with an addition?

Both following examples are ending in an error:
```
 .onDupUpdate('cents', 'cents + VALUES(cents)', { dontQuote: true })
```
```
 .onDupUpdate('cents = cents + VALUES(cents)', { dontQuote: true })
```

Can anybody please explain me what I'm doing wrong or is it simply currentyl not supported?

Currently I'm adding the "ON DUPLICATE KEY UPDATE ..." part by hand to the query string, but it would be of cause very nice to get in packed together with the squel command.

Regards

**Comment by hiddentao** [comment]
This seems to work for me:

```js
squel.insert().into('table').setFields({ name: 'test' }).onDupUpdate('cents = cents + VALUES(cents)').toParam();
```

**Comment by ronny332** [comment]
@hiddentao sorry for the delay, I will test your code asap. For my part of code where it was needed, a workaround was a quick and dirty solution but works until now ;-).
