### ISSUE TITLE
Will you include Schema creation support? (CREATE TABLE, etc.)

### ISSUE THREAD

**Issue by eliOcs** [hiddentao/squel#114]
I just found this package and I find it very useful. Is there another package or do you plan on adding the generation of `CREATE` SQL?

**Comment by leocaseiro** [comment]
Hi @hiddentao, I understand the best way to achieve this would be using [custom_queries](https://hiddentao.github.io/squel/index.html#custom_queries) as you mentioned at #99.

How about add an example at custom_queries to create a simple `Contacts` table?
I believe would help lot of users.

I loved this lib, btw.

**Comment by hiddentao** [comment]
@leocaseiro Glad you like it. I've updated the custom query example as requested -> file:///Users/ram/dev/js/squel/gh-pages/index.html#custom_queries

It's very basic and doesn't check for errors, but shows what's possible.

**Comment by leocaseiro** [comment]
Thank you so much! I'll use as a start. Very very nice!!!
