### ISSUE TITLE
unable to clone when using mssql flavour

### ISSUE THREAD

**Issue by henksmeba** [hiddentao/squel#120]
It looks like i'm unable to clone when using the mssql flavour. The same action succeeds when using no flavour. I get the following error:

TypeError: Cannot read property 'options' of undefined
    at TopBlock.ParentBlock (x:\dropbox\sync-framework\sql-couch-cache\node_modules\squel\squel.js:2324:62)
    at new TopBlock (x:\dropbox\sync-framework\sql-couch-cache\node_modules\squel\squel.js:2358:50)

**Comment by hiddentao** [comment]
Will look into this.

**Comment by henksmeba** [comment]
Looks like this is almost fixed. I only get [object object] when cloning an object with sub queries:

SELECT contract_job.contract_id, contract_job.contract_job_recid, contract_job.beurttype, __user FROM contract_job INNER JOIN ([object Object]) `lu` ON (lu.contract_job_recid = contract_job.contract_job_recid)

**Comment by greghart** [comment]
FWIW I've ran into a similar issue regardless of flavour, with what looks like the same root cause (cloning expressions in subqueries).

```javascript
var expression = squel.expr().and('a = 1');
console.log(squel.select().from('table').left_join('table_2', 't', expression).clone().toString());
// outputs 'SELECT * FROM table LEFT JOIN table_2 `t` ON ([object Object])'
```

**Comment by etreworgy** [comment]
+1

**Comment by hiddentao** [comment]
Is this still an issue?

**Comment by c4mden** [comment]
No, this seems to be working fine, and has been for quite a few months now.

Thank you!

On Mon, Jun 13, 2016 at 8:09 PM, Ramesh Nair <notifications@github.com>
wrote:

> Is this still an issue?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hiddentao/squel/issues/120#issuecomment-225753631>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA7DLQi24nJeuZ8q7JqSfC4AlLE9kHGOks5qLf88gaJpZM4DUKYz>
> .
>



-- 
*Camden Daily*
President & Founder
jaunter.com

**Comment by hiddentao** [comment]
Thanks.
