### ISSUE TITLE
Question: select static value?

### ISSUE THREAD

**Issue by pcothenet** [hiddentao/squel#123]
Hi,

I'm looking to do something like this:

SELECT 
a = 'staticValue'
table.b,
table.c
FROM table
(I want column a to always have the same value)

Is there an easy way to do this?

**Comment by pcothenet** [comment]
OK, looks like 

squel.select(sql_config)
.field('\'StaticValue\'::varchar(20)')
.field('table.b')
.field('table.c')
.from('table')

does the trick for PostgreSQL. 

Let me know if there's something more elegant to do this :)

**Comment by hiddentao** [comment]
That's pretty much how you have to do it. Squel allows you to do any string you want for the field specifier.

**Comment by pcothenet** [comment]
Thanks!
