### ISSUE TITLE
Support for CROSS JOIN

### ISSUE THREAD

**Issue by pcothenet** [hiddentao/squel#124]
I was able to do this by doing:

squel.cls.JoinBlock.prototype.cross_join = function(table, alias) {
      if (alias == null) {
        alias = null;
      }
      var condition = null;
      return this.join(table, alias, condition, 'CROSS');
    };

**Comment by hiddentao** [comment]
Will add in for next release.

**Comment by basickarl** [comment]
Might be a good idea to add this to the documentation, since it exists in the code.

**Comment by hiddentao** [comment]
It is already documented -> https://hiddentao.com/squel/api.html#select_cross_join
