### ISSUE TITLE
OUTPUT functionality does not work on DELETE statements in MSSQL

### ISSUE THREAD

**Issue by seanohollaren** [hiddentao/squel#135]
I'm attempting to use the following code to return the id of a deleted row:

    var sql = squel.delete()
            .from(annotationsTable)
            .where('id = ' + id)
            .output('id');

This generates the following SQL statement (with an input value of 61):

    DELETE FROM [UserProfiles].[dbo].[Annotations] 
    OUTPUT INSERTED.id 
    WHERE (id = 61)

If this were an INSERT or UPDATE operation, "INSERTED.id" would be the correct syntax, however, since this is a DELETE, it should actually be looking to "DELETED.id".  I've confirmed this should be the case by manually running the two SQL statements.

So, when functioning correctly, the above squel code should actually be generating:

    DELETE FROM [UserProfiles].[dbo].[Annotations] 
    OUTPUT DELETED.id 
    WHERE (id = 61)

Would it be possible to fix this behavior?

Thanks!

**Comment by seanohollaren** [comment]
For some background, it looks like this functionality was introduced in [this commit](https://github.com/hiddentao/squel/commit/850e0483906d1d8a3f434f992552ff42e7417a57) which was in response to [this issue](https://github.com/hiddentao/squel/issues/102).

**Comment by hiddentao** [comment]
Ah, thanks for spotting this. Will fix for the next release.

**Comment by seanohollaren** [comment]
Thanks!
