### ISSUE TITLE
support for "with statement" - common table expression

### ISSUE THREAD

**Issue by DmitryEfimenko** [hiddentao/squel#136]
It would be great if there was support for CTE:
```
with data
as
(
    select * from tblUser
)
select id from data
```

**Comment by onedr0p** [comment]
I am also interested in the feature :+1:

**Comment by hiddentao** [comment]
Will look into this for a future release.

**Comment by thynson** [comment]
+1

**Comment by lutcmoi** [comment]
Hi, as far as I used this lib the "with" and "with recursive" statements are the only ones missing.
I look forward to having it !
Is there a workaround for now ?

**Comment by hiddentao** [comment]
Somebody just needs to write a builder for with statements. Squel provides the necessary base classes for this to be easily done.

**Comment by warrenseymour** [comment]
Introduced by #239 which has just been merged

**Comment by DmitryEfimenko** [comment]
great! Closing this.
