### ISSUE TITLE
SQL_CALC_FOUND_ROWS

### ISSUE THREAD

**Issue by apetroff** [hiddentao/squel#137]
How can I add SQL_CALC_FOUND_ROWS into select query?

**Comment by apetroff** [comment]
And here is the answer:

```
.select({ autoQuoteTableNames: false, autoQuoteFieldNames: false })
.field("SQL_CALC_FOUND_ROWS content.id")
```

**Comment by sahara18** [comment]
how does it work further? i mean select found_rows() or something else

**Comment by apetroff** [comment]
You have to do do execute 2 queries in the same connection.
1. SELECT  SQL_CALC_FOUND_ROWS ...
2. SELECT FOUND_ROWS() as count

**Comment by sahara18** [comment]
i wouldn't have problems with it in sql, but i'm new in squel, my 2nd query looks like this:
squel.select().field('FOUND_ROWS()', 'count')
but i get error here as i miss "from"..

**Comment by apetroff** [comment]
I don't use squel for such a short quey. Squel is used for long dynamic query constructing.
So simply use "SELECT FOUND_ROWS() as count" as a string.

**Comment by sahara18** [comment]
did it, thanks a lot
