### ISSUE TITLE
Simplify the loading module

### ISSUE THREAD

**Issue by Smert** [hiddentao/squel#141]
Looks difficult:
```
delete require.cache[require.resolve('squel')];
var squel = require('squel');
squel.useFlavour('mysql');
delete require.cache[require.resolve('squel')];
```

Solution would be to clear the cache in module.exports getter (bad).
Or get rid of the singleton pattern. Set flavour in the constructor:
```
var squel = require('squel')('mysql'); // or require('squel').useFlacour('mysql')
```

**Comment by hiddentao** [comment]
Flavour setting is being refactored for the next release, so this problem will go away soon.

**Comment by hiddentao** [comment]
This has been sorted out in 3.11.0. Now the `useFlavour()` methods returns an instance of squel for that flavour, meaning you can easily switch flavours and use multiple flavours at the same time.
