### ISSUE TITLE
Feature: Case statements

### ISSUE THREAD

**Issue by DmitryEfimenko** [hiddentao/squel#143]
It would be great if expressions had support for case statements:
*Sql:*
```
case
    when name = 'Sam' then 'Allowed'
    when name = 'Tom' then 'Not Allowed'
end
```
*Expr:*
```
squel.expr().case()
    .when('name = ?', 'Sam').then('Allowed')
    .when('name = ?', 'Tom').then('Not Allowed')
    .end()
```

Keep in mind that the following sql `case` syntax is also possible:
```
case name 
    when 'Sam' then 'Allowed'
    when 'Tom' then 'Not Allowed'
end
```
*Expr:*
```
squel.expr().case('name')
    .when('?', 'Sam').then('Allowed')
    .when('?', 'Tom').then('Not Allowed')
    .end()
```

**Comment by hiddentao** [comment]
I didn't realise this was possible in SQL.

**Comment by bmc08gt** [comment]
Any update on this? Could really use this for the logic i need to implement into a query.

**Comment by hiddentao** [comment]
Sorry, been very busy lately. I'm looking to get back onto Squel tickets
over the next week or so. Will look into adding contributors too so that
I can share the workload.

On 04/08/2015 23:03, Brandon McAnsh wrote:
> Any update on this? Could really use this for the logic i need to
> implement into a query.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hiddentao/squel/issues/143#issuecomment-127642822>.
> 

-- 
Ramesh Nair

Freelance Web Developer

www.hiddentao.com
www.github.com/hiddentao

**Comment by SergeS** [comment]
Hi all, forked squel and working on this thing, as we also need this here

**Comment by hiddentao** [comment]
This is done now.
