### ISSUE TITLE
Postgres subquery in FROM breaks because alias requires 'as'

### ISSUE THREAD

**Issue by bleupen** [hiddentao/squel#148]
Hi there,

I want to use a subquery in the FROM clause of a postgres query:

```javascript
squel.useFlavour('postgres');
squel.select().from(squel.select().from('my_table'), 'my_table');
```

This generates the following:

```SELECT * FROM (SELECT * FROM my_table) `my_table````

which postgres doesn't like because it wants the alias to be prefixed with "as".

Any thoughts about a possible workaround? Thanks.

**Comment by olegsmetanin** [comment]
+1

**Comment by agentr13** [comment]
The issue isn't because of the missing *as*, but rather that the alias is being quoted in back-ticks rather than double-quotes.

This should work correctly:
```javascript
squel.useFlavour('postgres');
squel.select().from(squel.select({tableAliasQuoteCharacter: '"').from('my_table'), 'my_table');
```

Although there _is_ an issue in that the postgres flavor isn't configuring the table alias quote character automatically.

**Comment by hiddentao** [comment]
Yep, @agentr13 has it right.

You can also override the alias quote character for all your queries in one go:

```js
squelPostgres = squel.useFlavour('postgres');

squelPostgres.cls.DefaultQueryBuilderOptions.tableAliasQuoteCharacter = '"';

squelPostgres.select()
   .from( squelPostgres.select().from('my_table'), 'my_table')
   .toString();
```
