### ISSUE TITLE
Join, problems with char  " ` " in SQL Server

### ISSUE THREAD

**Issue by estvmachine** [hiddentao/squel#149]
I make this query:

```javascript
    squel.select().field('POTPR.NUMOT','NumOT')     
				   .field('POTL.NUMOT', 'NumSubOT')  	 
                                   .from('POTPR')
				   .join('POTL', 'POTL', 'POTL.IDPOTL= POTPR.IDPOTL')
				   .order('POTL.NUMOT')
				   .toString();
};
```

When i execute this query in SQL Server 2014, i got problems with the character  " ` ".

![image](https://cloud.githubusercontent.com/assets/2062668/7657018/98e51fd4-fafc-11e4-86ae-0102d12879c0.png)

When i use mssql-tedious driver i got this:

![image](https://cloud.githubusercontent.com/assets/2062668/7656967/10082684-fafc-11e4-89bb-6bb5c76814fd.png)

Its for the second parameter of 'JOIN'.

**Comment by hiddentao** [comment]
What quote character should be used?

You can override the quote character for aliases globally and on a per-instance basis -> http://hiddentao.github.io/squel/api.html#cls_defaultquerybuilderoptions

Also note that we have an `mssql` flavour available for use in squel. You might want to switch to that if appropriate.

**Comment by estvmachine** [comment]
Oh i try it tomorrow!, for the alias dont use character, and for the values use single quotes (').

So for the " ` "  i do a replace like this:
```javascript 
                    squel.select()...join().toString().replace(" ` " , "");
```

**Comment by estvmachine** [comment]
Works for me using flavour MSSQL, sorry at the moment works for me without that. :)
