### ISSUE TITLE
insert and select results

### ISSUE THREAD

**Issue by objectbb** [hiddentao/squel#150]
For whatever reason, in the browser (chrome), I can't seem to retrieve the two rows of data right after I insert them.  What am I doing wrong?  The insert results show 4 items but the select has 0.

var rsin = squel.insert()
    .into("test")
    .setFieldsRows([
        { name: "Thomas", age: 29 },
        { name: "Jane", age: 31 }    
    ]).toParam();
   
    var rs = squel.select().from("test").toParam();

**Comment by objectbb** [comment]
Additional information...this is occurring through a browser not Node.js.

**Comment by mattecapu** [comment]
probably the problem isn't in your squel query

**Comment by objectbb** [comment]
I appreciate the direction, but what will be the difference between setups on node.js vs web.  The documentation seems to have a node.js point-of-view.  If the web part is not as simple as just adding a script tag, where can I find this information?

**Comment by hiddentao** [comment]
I'm surprised it shows 4 items since you're only inserting 2 rows. What are you inserting the data into?

**Comment by objectbb** [comment]
Yes, I was confused about that as well. I'd included the code above, followed the documentation, ran it, and the instead of storing as two rows it was converted into an array of 4 items.

**Comment by objectbb** [comment]
![debug](https://cloud.githubusercontent.com/assets/835981/7709352/13c588ce-fe22-11e4-94bc-8047aa0a8cbf.png)

**Comment by mattecapu** [comment]
The values array is flattened, so a length of 4 is correct (2 rows with 2 fields each = 4 values)
How do you send the query to the database? How do you fetch the results? In what sense you get at first 4 results but then none? Can you post the SELECT query that fails to find any row?

**Comment by objectbb** [comment]
![untitled](https://cloud.githubusercontent.com/assets/835981/7712238/ba3633e4-fe35-11e4-9db2-c29895b67ebc.png)

**Comment by mattecapu** [comment]
Are you aware that generating a query with squel doesn't actually execute it on the database? You need some way to provide it to a DBMS.
The `values` array you're inspecting stores costants to insert in your query *before* providing them to the DBMS. It doesn't tell anything about the result of the query itself. See the documentation of `toParam()` for some example to examine.
Moreover, generating a query client side is absolutely **not safe**, because they can easily be modified by a third part. This is clearly stated on [squeljs.org]() (like, with a giant red banner, you know).

**Comment by objectbb** [comment]
I understand sql injection...I really thought the data was locally cache (webstorage)  i.e. (breezejs, jaysondata, firebase, etc) and squel.js provides a sql interface for it.

**Comment by hiddentao** [comment]
@objectbb  Nope, sorry, Squel just generates the query for you. As @mattecapu says you shouldn't be sending queries back to your server. The only valid use-case (IMO) for client-side Squel is if you're building a downloadable packaged app or doing Phonegap work.

**Comment by objectbb** [comment]
or a SPA

**Comment by hiddentao** [comment]
Am closing this issue as the central problem seem resolved.
