### ISSUE TITLE
fromQuery method isn't exposed

### ISSUE THREAD

**Issue by mattecapu** [hiddentao/squel#151]
The documentation [features this method](https://hiddentao.github.io/squel/#insert), and I can find it in the [source code](goo.gl/ylxg6f), but currently it isn't exposed in the API of the package.

![image](https://cloud.githubusercontent.com/assets/5738009/7711587/c2151ee6-fe6b-11e4-888f-ac4e1fcec298.png)

As you can see from the screenshot, it doesn't show up as a member of an INSERT query, and it's indeed `undefined`.

This issue was previously (6 months ago) reported [here](https://github.com/hiddentao/squel/issues/111#issuecomment-75347473) by @MayhemYDG.

If someone could point me a reference on how to expose it, I'll happily make the necessary work, but at this time I'm slightly less than clueless on how to "fix" this.

**Comment by mattecapu** [comment]
up?
For now I replaced my local installation of squel with the file downloaded from here (the one linked in the post above), but I really like to have it in an official release

**Comment by hiddentao** [comment]
Will make an update this week.

**Comment by mattecapu** [comment]
Thank you!

**Comment by hiddentao** [comment]
Now available in 3.11.0.
