### ISSUE TITLE
Postgresql having clause

### ISSUE THREAD

**Issue by banzai-samurai** [hiddentao/squel#152]
Good day,

Is it possible to use "having" clause of Postgresql in squel? 
Something like 

`squel.select().from('table', 't').left_join('table1, 't1', 't1.id = t1.id').field('t.name').field('count(t1.*)')
group('t.name').having('count(t1.*) > ?', 15);`

Do you plan to provide this feature?

**Comment by hiddentao** [comment]
Closing this as it's a duplicate of #86.
