### ISSUE TITLE
where clause error in latest build

### ISSUE THREAD

**Issue by ZeusIV** [hiddentao/squel#153]
had my package.json set like this
"squel": "^3.10.0"
and
squel.useFlavour('postgres');
was doing 
squel.select().from('users').where(providers[provider], profile.id).toParam();
which used to give me
text "SELECT * FROM users WHERE (googid = $1)" 
values ['xxxxxx']
did a clean npm install and picked up 3.11.0 and it broke most things. took me a while to track it down to squel which is now giving me 
text "SELECT * FROM users WHERE (googid = ?)" 
values ['xxxxxx']
and that breaks pg-promise which is looking for $n tokens
[Error: No variable $1 found for the value with index 0]
i'll just change my package.json 
"squel": "3.10.0"
for the time being

**Comment by hiddentao** [comment]
Ooh, I didn't realise that's how the `^` worked in the version specifier - I thought it only upgraded patch versions. I'm going to release v4.0.0 now and unpublish 3.11.0. Thanks for bringing this up.

**Comment by hiddentao** [comment]
Done. 4.0.0 released.

Btw, flavour usage has changed slightly in the latest release. This is how to do it now:

```js
var squelPostgres = squel.useFlavour('postgres');

squelPostgres.select()...
```

We now build an instance of squel just for that flavour. This allows you to switch between flavours quite easily and have multiple flavours on the go.

**Comment by hiddentao** [comment]
More info on caret (^) - http://fredkschott.com/post/2014/02/npm-no-longer-defaults-to-tildes/

**Comment by ZeusIV** [comment]
that was quick :)
i'll give v4 a whirl tomorrow
TIA

**Comment by schadov** [comment]
Is this kind of change really necessary? I mean if the library changes interface once in a while, it is a huge risk using it in production.

**Comment by hiddentao** [comment]
@schadov  That's why I upped the version number to 4.0 so that people who want the old way can still use 3.x.x. See http://semver.org/
