### ISSUE TITLE
Custom types changes

### ISSUE THREAD

**Issue by idonman** [hiddentao/squel#159]
New version of squel toString method now creates invalid raw sql when using custom types.

squel.registerValueHandler(Date, function(date) {
    return date.toISOString();
});

For example:
squel.insert().into('foo').set('bar', new Date()).toString() =>

Squel version 3.10.0:
//INSERT INTO foo (bar) VALUES ('2015-06-17T12:29:05.830Z') // valid sql

Squel version 4.0.0:
//INSERT INTO foo (bar) VALUES ((2015-06-17T12:29:05.830Z)) // invalid sql

**Comment by gigablah** [comment]
Should probably have tests for this :)

**Comment by gigablah** [comment]
Turns out there was a test, just that it was changed so that invalid SQL will pass:

https://github.com/hiddentao/squel/commit/cb33a417361da59b1fd530e07d426f32a52b4828#diff-f990948e5816cc868421fdab6593e591R152

**Comment by hiddentao** [comment]
This was changed since we no longer wanted to assume that the custom value needed to be formatted as a string. Thus change your handler to:

```js
squel.registerValueHandler(Date, function(date) {
  return "'" + date.toISOString() + "'";
});
```
