### ISSUE TITLE
Support for new Postgres JSONB operators?

### ISSUE THREAD

**Issue by DecayConstant** [hiddentao/squel#166]
In Postgres 9.4 there are new operators that work on the new JSONB datatype. The problem is that three  of these operators  ( ? , ?| , ?&)  contain question marks, which are automatically assumed to be placeholders for parameterized data in Squel.

Is there a way to force a question mark to appear in a WHERE or ON clause?  I couldn't find any.

http://www.postgresql.org/docs/9.4/static/functions-json.html#FUNCTIONS-JSONB-OP-TABLE

**Comment by hiddentao** [comment]
We probably need an option to specify the placeholder character.

**Comment by hiddentao** [comment]
The placeholder character is now configurable -> https://github.com/hiddentao/squel/blob/master/src/squel.coffee#L99

**Comment by hiddentao** [comment]
The way to do this now is to select some other character as the parameter placeholder (using `parameterCharacter` option) and then happily go ahead and use the JSON operators accordingly.
