### ISSUE TITLE
(SECURITY+CRITICAL) SQL Injection

### ISSUE THREAD

**Issue by sergiofilhowz** [hiddentao/squel#168]
Squel is not escaping string characters before applying parameters:

    var login = "' OR 1=1 OR '' = '";
    var query = squel.select().from('user').where('login = ?', login).toString();

result will be

    SELECT * FROM user WHERE (login = '' OR 1=1 OR '' = '')

**Comment by hiddentao** [comment]
The `toString()` method is not going to generate safe queries. You're better off using `toParam()` instead and then passing the query and parameter values through to your db engine's querying methods.

**Comment by sergiofilhowz** [comment]
Thanks for your tips.
I've searched for a solution to this problem with sequelize and here it is for someone else with this problem:

    var select = this.selectQuery.toParam();
    return sequelize.query(select.text, {
        replacements : select.values
    });
