### ISSUE TITLE
Bug in custom value handler examples

### ISSUE THREAD

**Issue by tcort** [hiddentao/squel#169]
squel.registerValueHandler(Date, function(date) {
      return date.getFullYear() + '/' + date.getMonth() + '/' + date.getDate();
    });

[date.getMonth()](http://www.w3schools.com/jsref/jsref_getmonth.asp) is 0 indexed (January=0, February=1, ...), but SQL dates are 1 indexed (January=1, February=2, ...).

```
squel.update().
  .table('students')
  .set('start_date', new Date(2013, 5, 1))
  .toString()

// UPDATE students SET start_date = '2013/5/1'
```

In the example above, the JavaScript date object is June 1, 2013, but the SQL date is May 1, 2013.

This off by one error with `getMonth()` appears in examples in the `README.md` as well as the website.

**Comment by hiddentao** [comment]
Thanks, this is now fixed.
