### ISSUE TITLE
SQL INJECTION ( update in MySQL)

### ISSUE THREAD

**Issue by udarkness** [hiddentao/squel#174]
The following leads to an injection:
sql.set("field", "value'");
it results in: UPDATE table SET 'value'';
more severe: sql.set("field", "' + (SELECT count(*) FROM other_table) + '");

**Comment by smaili** [comment]
Should this be the builder's responsibility?  To me, this does nothing more than take away the syntax of sql.  The driver you give the built query to should be responsible for proper value handling.

**Comment by hiddentao** [comment]
Yep, squel already allows you to build parameterized queries which you can then pass to your db driver for safe value insertion.

**Comment by udarkness** [comment]
I think this was closed prematurely.
The issue is simple:
The builder attempts to sanitize this, please note it is adding ' but in a wrong way.
It would be acceptable if you say the builder is not trying at all and it is responsibility of the driver.
But in this moment, it is something uncomfortable in the middle (doing it, but failing)
Parametrized queries are only useful for bulk executions, and that is rarely the case. (to not repeat the query parsing and execution plan).
Possible solutions: to deprecate the option to build a direct statement, or to add the possibility to sanitize it with a connection, like other builders do. for example: squel.addConnection(connection). and use the escape function while generating the query. https://github.com/felixge/node-mysql#escaping-query-values (mysql example). If a connection is not set, it must at least add \ before ' (easy to implement) in order to generate a valid sql query.

For smaili, the builder is not building a valid sql query, just try to execute it and see.

**Comment by smaili** [comment]
```
I think this was closed prematurely.
The issue is simple:
The builder attempts to sanitize this, please note it is adding ' but in a wrong way.
```

I apologize @udarkness, I did not realize that.  I 100% am against any kind of sanitization, otherwise this is stepping into the territory of a driver which there's no need for.  Although this is just my opinion, but if majority of people think it's better to have sanitizing then so be it.

**Comment by hiddentao** [comment]
Ok, I see your point. At this moment the philosophy of squel is that it's more the developer's responsibility to ensure that their queries are safe. Although it's tempting to remove the builder stringifications I think it could be an inconvenience in certain situations where simple queries are being made. Though I am warming to the idea of doing so.

**Comment by udarkness** [comment]
If that is not the case, I recommend to add to the docs an important note that says: Note: This library is not compatible with strings that contains apostrophes ', examples: "No, I don't".

Maybe it sounds a little hilarious, but I think it is recommended to warn the users that apostrophes are not compatible with squel.

**Comment by hiddentao** [comment]
Perhaps we can instead inform users that they must quote their apostrophes, e.g. `\'`.

**Comment by udarkness** [comment]
Your direct rival already handle this issue properly: http://knexjs.org/#Raw, in **squel all is raw**, other builders(php): http://kohanaframework.org/3.3/guide/database/query/builder they also offer the option to keep it safe (raw, no raw).
According to the description of your project "**lightweight Javascript library for building SQL query strings.**", squel must be able to generate SQL queries.
Sorry for that, but "*UPDATE table SET 'don't work';*" is NOT a SQL query (not standard, not vendor specific)

**Comment by smaili** [comment]
`
Your direct rival already handle this issue properly: http://knexjs.org/#Raw, in squel all is raw, other builders(php): http://kohanaframework.org/3.3/guide/database/query/builder they also offer the option to keep it safe (raw, no raw).
`

I understand what you're saying, but I don't think this is a fair comparison because those examples are intended to be an all-in-one, while squel is intended to be a pure query builder.  That's why it says `lightweight Javascript library for building SQL query strings`.

As I said, I don't mind having this as an option that can be enabled - but I am against making it a default behavior.  For those of us that already use a driver separately from the query building, it's extremely inefficient to have it done twice.  If what you're looking for is a single all-in-one library that automatically does everything for you then I recommend you use Knex.

**Comment by hiddentao** [comment]
Yes I agree with @smaili , an option that can be enabled is probably best. I'm trying to figure out the best way of implementing the escaping. Perhaps a built-in method which you can then override globally on a per query builder instance.
