### ISSUE TITLE
Table names are not escaped

### ISSUE THREAD

**Issue by oliversalzburg** [hiddentao/squel#175]
I'm trying to build a query like this:
```js
var query = squel.update()
				.table( "user" )
				.where( "id = ?", result.id )
				.returning( "*" );
```
But the resulting query will fail, because `user` is not escaped.

**Comment by oliversalzburg** [comment]
Similarly, column names that are in camelCase, aren't escaped either. Why isn't *everything* simply wrapped in the appropriate quotes? Am I missing something obvious here?

**Comment by hiddentao** [comment]
Try using `squel.update({ autoQuoteTableNames:true, autoQuoteFieldNames:true })`. See http://hiddentao.github.io/squel/api.html#cls_defaultquerybuilderoptions

**Comment by oliversalzburg** [comment]
@hiddentao Ah! Thanks for the help. I completely missed that when I browsed the docs. 

Why isn't this the default behavior though? It seems more safe to always escape. Is there a downside I'm not aware of?

**Comment by hiddentao** [comment]
To be honest I'm not sure and very few people have asked about that before.

**Comment by HarryPehkonen** [comment]
I'd be very happy if this was the default behaviour.  I assume it should be part of the flavour.  For example, with PostgreSQL, I routinely turn on quotes for field names, and set the quote character to ".
