### ISSUE TITLE
Two statements in one go

### ISSUE THREAD

**Issue by DmitryEfimenko** [hiddentao/squel#178]
Lets say I have two `update` statements to run, but I don't want to make two calls to the database. How can I achieve this? I thought something like the below, but it didn't work:
```javascript
var data = [
    { id: 1, name: 'Bob' },
    { id: 2, name: 'Mark' }
];
var sql = squel;
for(var i = 0, l = data.length; i < l; i++) {
    sql = sql.update()
        .table('myTable')
        .set('name', data[i].name)
        .where('id = ?', data[i].id);
}
sql = sql.toParam();
executeSql(sql);
```
expected sql is:
```sql
update myTable set name = 'Bob' where id = 1;
update myTable set name = 'Mark' where id = 2;
```

**Comment by hiddentao** [comment]
I'm not sure if what you're asking for is technically possible since the value you are updating - `name` - is dependent up on the the `id`.  It depends on your db engine I suppose. Squel only builds the query string for you - it cannot and does not handle query optimization.
