### ISSUE TITLE
SELECT nextval('sequence_id_seq')

### ISSUE THREAD

**Issue by zarmack** [hiddentao/squel#181]
Hi !

I'm using PostgreSQL 9.4 and i'm triing to retieve the nextval from a sequence.
I don't find the solution to build the query ````"SELECT nextval('sequence_id_seq')````

Actually I'm using a trick:

````
var q = squel.select();
q.field("nextval('users_register_id_seq')");
q.from('users_register');
q.limit(1);
````

Is there a best way to get the nextval ?

Regards,
Zarmack

**Comment by hiddentao** [comment]
You should be able to do:

```js
squel.select().function('nextval(?)', 'sequence_id_seq').toString();
```
