### ISSUE TITLE
.useFlavour('db2')

### ISSUE THREAD

**Issue by willfarrell** [hiddentao/squel#183]
- *offset:*
 - `ROW_NUMBER() Hack` allowed by default
 - `WHERE ROWNUM BETWEEN n AND 10` [requires db2 settings change](https://www.ibm.com/developerworks/community/blogs/SQLTips4DB2LUW/entry/limit_offset?lang=en)
 - `LIMIT n,10` -> `LIMIT 10 OFFSET n` [requires db2 settings change](https://www.ibm.com/developerworks/community/blogs/SQLTips4DB2LUW/entry/limit_offset?lang=en)
- *limit:* `LIMIT 0,n` -> `FETCH FIRST [n] ROWS ONLY`

**Comment by willfarrell** [comment]
Turns out `LIMIT 10 OFFSET n` is supported when you don't specify a flavour. Note to anyone who runs into this. be sure to run the script below to enable the functionality.

```
DB2_COMPATIBILITY_VECTOR=MYS
# OR DB2_COMPATIBILITY_VECTOR=4000
db2stop
db2start
```

**Comment by brandonros** [comment]
I'm confused. Was there a pull request for this?

**Comment by willfarrell** [comment]
No PR, the DB just needs to be configured to allow it to work.
