### ISSUE TITLE
Current Flavour

### ISSUE THREAD

**Issue by C1nde** [hiddentao/squel#192]
Hello.

Is it possible to get currently used flavour?

For example:
```
var squel = require('squel').useFlavour('postgres');
```

How can I get current flavour? I believe there should be function like `getFlavour` or `flavour` property. Cannot find it, maybe it's there and that's just me?

Thanks

**Comment by hiddentao** [comment]
At the moment there isn't but we can probably add a function.

**Comment by hiddentao** [comment]
Thanks for the PR.
