### ISSUE TITLE
dose .where("field = ?", value) consider sql injection?

### ISSUE THREAD

**Issue by figozhu** [hiddentao/squel#194]
will auto Escaping the value?

**Comment by idonman** [comment]
For postgres one of the way to avoid sql injection is to use toParam method, that returns text and values for parametrized queries.

See "Parametrized Queries" block:
https://github.com/brianc/node-postgres/wiki/Prepared-Statements

**Comment by hiddentao** [comment]
Yeah, toParam() is the method to use.

On 3 December 2015 at 17:39:32, FigoZhu (notifications@github.com) wrote:

will auto Escaping the value?
