### ISSUE TITLE
Squel roadmap - v5

### ISSUE THREAD

**Issue by hiddentao** [hiddentao/squel#201]
The use-cases for Squel are now increasing in complexity and I think it's time for a major rewrite of the codebase. 

**ES6** - Squel was originally written a long time ago in CoffeeScript, and more than one person has previously commented that they would contribute a PR if it wasn't for the choice of language. It's time for an ES6 rewrite using Babel.

**Nested queries** - Nesting queries within queries and expressions within expressions (#108, #160 ) should be made a lot easier to do. Right now, we basically allow for nesting in certain parts of certain queries and try and control this. I think it would be easier to just make nesting possible across the board and place the burden of correctness on the API user. Examples:

```js
squel.update().table(squel.select().from('students')).where('id IN ?', squel.select().from('ids'))
/// UPDATE (SELECT * FROM students) WHERE id IN (SELECT * FROM ids) 

squel.expr().and('b = ?', 2).and(squel.expr().and('test1 = ?', 1)).toParam()
// { text: "(b = ? AND (test1 = ?))", values: [2, 1] }
```

**Examples for API method docs** - #176 - Documentation is decent but usage examples should be added.

**Comment by hasan3ysf** [comment]
Why using Babel, why not using the 'use strict' mode only?

**Comment by mattecapu** [comment]
@hasan3ysf Babel makes it easier to support a broad range of js environments with the benefit of using ES2015 features not supported by all of them. Deploying ES2015 code as-is is still not feasible.
Babel transpiles to strict code by default, anyway.

**Comment by hiddentao** [comment]
ES6 port with Babel done.

**Comment by hiddentao** [comment]
Rewrite complete, v5 is released!
