### ISSUE TITLE
[TypeScript] Create typing for squel

### ISSUE THREAD

**Issue by Tomino2112** [hiddentao/squel#206]
Hi,

Anyone has the skill/time to create typing for this great package and submit it to https://github.com/DefinitelyTyped/DefinitelyTyped ?

I could do it in about a month, but maybe someone else has the time?

**Comment by hiddentao** [comment]
Perhaps this can wait until v5 is done - #201

**Comment by warrenseymour** [comment]
I have a fork with a few recent additions at https://github.com/warrenseymour/squel.d.ts that may be able to tide you over

**Comment by hiddentao** [comment]
@warrenseymour That's nice!

**Comment by alexturek** [comment]
@hiddentao Would you accept a PR of @warrenseymour's typescript definitions into this package? I'd like to use this project from a Typescript service I'm working on.

Typescript [recommends](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) publishing the definitions directly into the project, which IMO makes more sense anyways - it'll be easier to spot discrepancies and fix them if they're next to the code they describe.

**Comment by alexturek** [comment]
Note - @warrenseymour I think I'd want to modify those type definitions slightly - they seem to not be namespaced within `squel`, so `import * as squel from 'squel';` is polluting my global namespace.

**Comment by warrenseymour** [comment]
@alexturek Agreed, those definitions are pretty ropey; I forked an under-loved project and added just the definitions I needed at the time. They seem to have garnered some interest recently so I can revisit and clean them up, if nobody else takes up the challenge before I get to it.

**Comment by hiddentao** [comment]
More than happy to accept a PR. I'm not familiar with TypeScript myself though so will have to trust your judgements on it.

**Comment by demurgos** [comment]
Should be closed by #322

**Comment by hiddentao** [comment]
Thanks @demurgos
