### ISSUE TITLE
registerValueHandler not producing right values on insert?

### ISSUE THREAD

**Issue by Tomino2112** [hiddentao/squel#212]
Hi, 

I am probably doing something wrong here. I want to parse `Date` into format: `yyyy-MM-dd HH:mm:ss` 

I register the handler: 

```
squel.registerValueHandler(Date, (date: Date) => {
    return date.getFullYear() + "-" +
        (date.getMonth() + 1) + "-" +
        date.getDate() + " " +
        (date.getHours() < 10 ? "0" : "") + date.getHours() + ":" +
        (date.getMinutes() < 10 ? "0" : "") + date.getMinutes() + ":" +
        (date.getSeconds() < 10 ? "0" : "") + date.getSeconds();
});
```

and create the Insert query

```
...
.set("created_timestamp", new Date())
...
```

and when I stringify the query, here is what I get:

```
Running SQL query: INSERT INTO pages_docsname (created_timestamp, created_by_id, modified_timestamp, modified_by_id, user_id, pattern, page_id, domain_id) VALUES ((2016-2-25 12:17:20), 3122, (2016-2-25 12:17:20), 3122, 3122, 'something', 10, 328)
```

So obviously the handler is working fine, but for some reason instead of parsing the value as a string it adds brackets around it. 

What am I doing wrong?

**UPDATE**
If I add apostrophes manually:

```
squel.registerValueHandler(Date, (date: Date) => {
    return "'" + date.getFullYear() + "-" +
        (date.getMonth() + 1) + "-" +
        date.getDate() + " " +
        (date.getHours() < 10 ? "0" : "") + date.getHours() + ":" +
        (date.getMinutes() < 10 ? "0" : "") + date.getMinutes() + ":" +
        (date.getSeconds() < 10 ? "0" : "") + date.getSeconds() + "'";
});
```

Query works, but still adds brackets `... VALUES (('2016-2-25 12:17:20')...)`

**Comment by hiddentao** [comment]
Yes, you have to add apostrophes manually to make it work - that's intentional as some value handlers may choose to return non-string values. It will still add the brackets as a safety measure.

**Comment by hiddentao** [comment]
As of v5, brackets no longer get added if the returned value is not a string.
