### ISSUE TITLE
Omit brackets in WHERE clause could produce better readability

### ISSUE THREAD

**Issue by bboyz269** [hiddentao/squel#215]
Since we have `squel.expr` for expresion building, I think removing the default bracket in `WHERE` clause will make the query "cleaner". If there's not a case in which bracket is required, would you please consider it?
Thanks a ton!

1.`quel.select().from("TABLE").where("A");`
```sql
    -- GOOD
    SELECT * FROM TABLE WHERE (A)
    -- BETTER
    SELECT * FROM TABLE WHERE A
```
2.`squel.select().from("TABLE").where("A").where("B");`
```sql
    -- GOOD
    SELECT * FROM TABLE WHERE (A) and (B)
    -- BETTER
    SELECT * FROM TABLE WHERE A and B
```
3.`squel.select().from("TABLE").where(squel.expr().or("A").or("B"));`
```sql
    -- GOOD (inconsistency with case 2)
    SELECT * FROM TABLE WHERE (A or B)
    -- BETTER
    SELECT * FROM TABLE WHERE A or B
```
4.
```javascript
squel.select().from("TABLE").where(
    squel.expr()
        .or_begin().and("A1").and("A2").end()
        .or_begin().and("B1").and("B2").end()
        .or("C")
)
```
```sql
    -- GOOD
    SELECT * FROM TABLE WHERE ((A1 AND A2) OR (B1 AND B2) OR C)
    -- BETTER
    SELECT * FROM TABLE WHERE (A1 AND A2) OR (B1 AND B2) OR C
```

**Comment by hiddentao** [comment]
The default brackets are there just in case an expression builder or a custom value handler returns a phrase which needs to be wrapped in brackets. If we didn't have extra brackets we may occasionally end up with a situation where there are no brackets even when there should be. Yes it's less readable but I think that's a price worth paying for correctness.

**Comment by hiddentao** [comment]
Made some improvements in 5.1.0 which should reduce the number of brackets.
