### ISSUE TITLE
Squel's browser compatibility

### ISSUE THREAD

**Issue by bboyz269** [hiddentao/squel#217]
Hi. I understand that squel is intended for server side but I wonder if browser compatibility is posted somewhere?

After running quick test, it seems that squel breaks in IE8 dues to the usages of Array.prototype.filter. I think it would be nice that you can spare a little effort and make it IE8-compatible too.

Thanks!

**Comment by hiddentao** [comment]
IE8 support is out of scope. Even Microsoft no longer support it -> https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support.

If you really need to get this working I suggest using a polyfill library alongside squel such as https://github.com/plusdude/array-generics
