### ISSUE TITLE
Field parameter

### ISSUE THREAD

**Issue by caliber01** [hiddentao/squel#218]
I have a problem figuring out how to set a field parameter. I would like to extract it then to the parameters list to also use node-postgres's sanitation. Is there any chance I could do something like this? Thank you.

```javascript
var query = 'foo';
var selection = squel.select()
    .field('items.*')
    .field('ts_rank_cd(search_vector, to_tsquery(?))', query)
    .from('items');
```

**Comment by hiddentao** [comment]
You could try using `squel.fval()`, see http://hiddentao.github.io/squel/#parameters

So

```js
var selection = squel.select()
    .field('items.*')
    .field(squel.fval('ts_rank_cd(search_vector, to_tsquery(?))', query))
    .from('items');
```

**Comment by hiddentao** [comment]
As of v5 `fval` as has been renamed to `str` so:

```js
var selection = squel.select()
    .field('items.*')
    .field(squel.str('ts_rank_cd(search_vector, to_tsquery(?))', query))
    .from('items');
```
