### ISSUE TITLE
Update to 4.4.2 crash on squel component registration as global variable in browser

### ISSUE THREAD

**Issue by alexseik** [hiddentao/squel#222]
When I've tried update from 4.3.2 to 4.4.2 I got Uncaught TypeError: Cannot set property 'squel' of undefined,
ReferenceError: squel is not defined,

in squel.js line 54,

root.squel = factory() //root is not defined!

PD: I'm not sure if this is a bug or I am doing something wrong in my distribution process. I'm building my project with bower.

**Comment by alexseik** [comment]
As a workaround I change the line 54 in squel.js 
root.squel = factory()
by
window.squel = factory()

**Comment by hiddentao** [comment]
I'm releasing v5 today which will (hopefully) have this fixed.
