### ISSUE TITLE
Query Creation adding custom Array Prototype methods as parameters

### ISSUE THREAD

**Issue by macharborguy** [hiddentao/squel#223]
Node version : 4.1.2
Squel version : 4.4.0

(note: while writing this i noticed that Squel was updated to version 5.  i updated to it to see if it fixed the below issue, but a new one has come up)

**With Version 4.4.0 of Squel**

I am working on a chat bot for our Twitch channel using NodeJS with Squel formatting the queries.  

I started adding prototype methods to the Array class object, those being .average(), .max() and .sum().

here is one of the queries that I am generating....

**SQUEL code for creating the query**

`let user_sync_query = squel.update()
					.table('users')
					.where('id = ?', user.id)
						.set('active', ( user.active ? 1 : 0 ) )
						.set('regular', ( user.regular ? 1 : 0 ) )
						.set('moderator', ( user.moderator ? 1 : 0 ) )
					.toParam();`

When I do a console.log of the 'user_sync_query' variable, this is what I get back...

` { text: 'UPDATE users SET active = ?, regular = ?, moderator = ?, function (){\n\tlet sum = 0, j = 0;\n\tlet arrLength = this.length;\n\tfor (let i = 0, item = this[i]; i < arrLength, isFinite(item); i++){\n\t\tsum += parseFloat(item); ++j;\n\t}\n\treturn j ? sum / j : 0;\n} = ?, function (){\n\tlet sum = 0;\n\tlet arrLength = this.length;\n\tfor (let i = 0, item = this[i]; i < arrLength, isFinite(item); i++){\n\t\tsum += parseFloat(item);\n\t}\n\treturn sum;\n} = ?, function (){\n\treturn Math.max.apply(Math, this.map(function(o){\n\t\treturn o.y;\n\t}));\n} = ?, function (from, to) {\n    var rest;\n    rest = this.slice((to || from) + 1 || this.length);\n    this.length = from < 0 ? this.length + from : from;\n    return this.push.apply(this, rest);\n  } = ? WHERE (id = ?)',
  values: [ 1, 1, 1, [Function], [Function], [Function], [Function], 1 ] }`

As you can see, active, regular and moderator are all being set correctly, but then additional params are added in, those params being the plain text of the 3 prototypes that i added to Array.   Removing the prototypes and making them normal functions fixes the issue, but i would rather keep the prototypes for the cleaner code.

**With version 5 of Squel**

Having updated to the latest version, i now get the following...

**Stack Trace**
`TypeError: str.substr is not a function,`
`at _class7._buildString (/.../node_modules/squel/squel.js:621:19),`
`at _class7._buildManyStrings (/.../node_modules/squel/squel.js:693:36),`
`at _class7._toParamString (/.../node_modules/squel/squel.js:1158:21),`
`at /.../node_modules/squel/squel.js:2720:20",`
`at Array.map (native),`
`at _class28._toParamString (/.../node_modules/squel/squel.js:2719:40),`
`at _class28.toParam (/.../node_modules/squel/squel.js:752:21),`
`at _getUsersFromDB (/.../lib/internals/UserManager.js:563:84)`

and the code at line number 563 of UserManager.js is the following...

`let query_users = squel.select().from('users').where('active = ?',1).order('id').toParam()`

the above query creation ran in 4.4.0 with no issue at all.  Since it is causing this error now, the program does not have a chance to get to where the other issue i mentioned at the start of the post happens.

Any help or suggestions appreciated.

**Comment by macharborguy** [comment]
So i did some tests today, adding console.log calls to each of the functions listed in the above stack trace.

From the looks of it, in _class7._buildString, line number 621...

`if (str.substr(idx,paramChar.length) === paramChar) {`

the value of **str** is apparently being set to a **[Function]**.  Using **str.toString()**, i was able to see very clearly that my custom Array.prototype methods are being treated as potential values to be inserted into the query, and are causing an error (since Functions do not have a substr method associated with them).

Below is the results of console.log calls right before each and every line in the stack trace, going from bottom to top.

_Note, I commented out ALL of my custom prototypes testing this out.  It made no difference.  Either I just screwed something up that is unrelated to those prototypes, or something else really weird is going on.  Below is the results with all of my custom prototypes removed._



**at _getUsersFromDB (/.../lib/internals/UserManager.js:563:84)**
**starting code is as follows**: `let query_users = squel.select().from('users').where('active = ?', 1).order('id').toParam();`




**at _class28.toParam (/.../node_modules/squel/squel.js:752:21),**
**arguments**:  {}

**options**:  {}




**at _class28._toParamString (/.../node_modules/squel/squel.js:2719:40),**
**arguments**:  { '0': { buildParameterized: true } }

**options**:  { autoQuoteTableNames: false,
  autoQuoteFieldNames: false,
  autoQuoteAliasNames: true,
  useAsForTableAliasNames: false,
  nameQuoteCharacter: '`',
  tableAliasQuoteCharacter: '`',
  fieldAliasQuoteCharacter: '"',
  valueHandlers: [],
  parameterCharacter: '?',
  numberedParameters: false,
  numberedParametersPrefix: '$',
  numberedParametersStartAt: 1,
  replaceSingleQuotes: false,
  singleQuoteReplacement: '\'\'',
  separator: ' ',
  buildParameterized: true }

**this.options**:  { autoQuoteTableNames: false,
  autoQuoteFieldNames: false,
  autoQuoteAliasNames: true,
  useAsForTableAliasNames: false,
  nameQuoteCharacter: '`',
  tableAliasQuoteCharacter: '`',
  fieldAliasQuoteCharacter: '"',
  valueHandlers: [],
  parameterCharacter: '?',
  numberedParameters: false,
  numberedParametersPrefix: '$',
  numberedParametersStartAt: 1,
  replaceSingleQuotes: false,
  singleQuoteReplacement: '\'\'',
  separator: ' ' }




**at Array.map (native),**
**at /.../node_modules/squel/squel.js:2720:20",**
**b**:  _class6 {
  options: 
   { autoQuoteTableNames: false,
     autoQuoteFieldNames: false,
     autoQuoteAliasNames: true,
     useAsForTableAliasNames: false,
     nameQuoteCharacter: '`',
     tableAliasQuoteCharacter: '`',
     fieldAliasQuoteCharacter: '"',
     valueHandlers: [],
     parameterCharacter: '?',
     numberedParameters: false,
     numberedParametersPrefix: '$',
     numberedParametersStartAt: 1,
     replaceSingleQuotes: false,
     singleQuoteReplacement: '\'\'',
     separator: ' ' },
  _str: 'SELECT' }
**b**:  _class7 {
  options: 
   { autoQuoteTableNames: false,
     autoQuoteFieldNames: false,
     autoQuoteAliasNames: true,
     useAsForTableAliasNames: false,
     nameQuoteCharacter: '`',
     tableAliasQuoteCharacter: '`',
     fieldAliasQuoteCharacter: '"',
     valueHandlers: [],
     parameterCharacter: '?',
     numberedParameters: false,
     numberedParametersPrefix: '$',
     numberedParametersStartAt: 1,
     replaceSingleQuotes: false,
     singleQuoteReplacement: '\'\'',
     separator: ' ' },
  _strings: [],
  _values: [] }




**at _class7._toParamString (/.../node_modules/squel/squel.js:1158:21),**
**arguments**:  { '0': 
   { buildParameterized: true,
     queryBuilder: 
      _class28 {
        options: [Object],
        blocks: [Object],
        function: [Function],
        distinct: [Function],
        fields: [Function],
        field: [Function],
        from: [Function],
        join: [Function],
        left_join: [Function],
        right_join: [Function],
        outer_join: [Function],
        left_outer_join: [Function],
        full_join: [Function],
        cross_join: [Function],
        where: [Function],
        group: [Function],
        having: [Function],
        order: [Function],
        limit: [Function],
        offset: [Function],
        union: [Function],
        union_all: [Function] } } }
**options**:  { buildParameterized: true,
  queryBuilder: 
   _class28 {
     options: 
      { autoQuoteTableNames: false,
        autoQuoteFieldNames: false,
        autoQuoteAliasNames: true,
        useAsForTableAliasNames: false,
        nameQuoteCharacter: '`',
        tableAliasQuoteCharacter: '`',
        fieldAliasQuoteCharacter: '"',
        valueHandlers: [],
        parameterCharacter: '?',
        numberedParameters: false,
        numberedParametersPrefix: '$',
        numberedParametersStartAt: 1,
        replaceSingleQuotes: false,
        singleQuoteReplacement: '\'\'',
        separator: ' ' },
     blocks: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     function: [Function],
     distinct: [Function],
     fields: [Function],
     field: [Function],
     from: [Function],
     join: [Function],
     left_join: [Function],
     right_join: [Function],
     outer_join: [Function],
     left_outer_join: [Function],
     full_join: [Function],
     cross_join: [Function],
     where: [Function],
     group: [Function],
     having: [Function],
     order: [Function],
     limit: [Function],
     offset: [Function],
     union: [Function],
     union_all: [Function] } }
**this._strings**:  []
**this._values**:  []




**at _class7._buildManyStrings (/.../node_modules/squel/squel.js:693:36),**
**strings**:  []
**strValues**:  []
**arguments**:  { '0': [],
  '1': [],
  '2': 
   { buildParameterized: true,
     queryBuilder: 
      _class28 {
        options: [Object],
        blocks: [Object],
        function: [Function],
        distinct: [Function],
        fields: [Function],
        field: [Function],
        from: [Function],
        join: [Function],
        left_join: [Function],
        right_join: [Function],
        outer_join: [Function],
        left_outer_join: [Function],
        full_join: [Function],
        cross_join: [Function],
        where: [Function],
        group: [Function],
        having: [Function],
        order: [Function],
        limit: [Function],
        offset: [Function],
        union: [Function],
        union_all: [Function] } } }

**within the '_for(var idx in strings) {_' loop**
**idx**:  remove
**strings[idx]**:  function (from, to) {
    var rest;
    rest = this.slice((to || from) + 1 || this.length);
    this.length = from < 0 ? this.length + from : from;
    return this.push.apply(this, rest);
  }
**strValues[idx]**:  function (from, to) {
    var rest;
    rest = this.slice((to || from) + 1 || this.length);
    this.length = from < 0 ? this.length + from : from;
    return this.push.apply(this, rest);
  }




**at _class7._buildString (/.../node_modules/squel/squel.js:621:19),**
**right before the '_while (str.length > idx) {_' line
**str**:  function (from, to) {
    var rest;
    rest = this.slice((to || from) + 1 || this.length);
    this.length = from < 0 ? this.length + from : from;
    return this.push.apply(this, rest);
  }






Doing some more research, according to this StackOverflow post: http://stackoverflow.com/questions/18878347/javascript-array-prototype-being-printed-almost-everywhere

> Use proper for (var i=0; i<arr.length; i++) loops for iterating arrays. for in enumerations will enumerate prototype properties as well, do not use them on arrays.

Looking back at '_class7._buildManyStrings' in the stack trace, notice that 'idx' has a value of 'remove'.  It appears to have enumerated over Array methods.

**Comment by macharborguy** [comment]
Doing some more tests now, installing each previous version of Squel.  The most recent version of Squel that works as it did before, for me, appears to be 4.3.2.  It does not give me any errors and all queries appear to be generated properly.  Ill stick with this one for now.

**Comment by hiddentao** [comment]
Thanks so much for testing this out. I think I will go through the code and replace the way loops are done to ensure this problem doesn't occur.

**Comment by hiddentao** [comment]
Fixed in 5.0.1
