### ISSUE TITLE
empty where clause

### ISSUE THREAD

**Issue by ZeusIV** [hiddentao/squel#226]
Hi,
Amazing bit of code. 
Been trying out node-mssql and tried to plug it in alongside my postgress data layer. First problem is that it doesn't take an array for parameters and it needs a datatype. I only need ints and strings so knocked up a quick function to take the node-mssql prepared statement
exports.msPrepare = function (sql, ps, query) {
        var sqlp = {};
	for (var i = 0; i < query.values.length; i++) {
		ps.input('p' + (i+1), isNaN(query.values[i]) ? sql.VarChar : sql.Int);
		sqlp['p' + (i+1)] = query.values[i];
	}
	return { text: query.text, values: sqlp };
};
and set var ssql = squel.update({ numberedParameters: true, numberedParametersPrefix: '@p' })
A bit sloppy but it got me going. Is there a way to get a json object for params out of squel?? squel.toParam('asObject') perhaps? 
I then hit a snag. In postgress I was using NOW() for the current date on an update and it worked fine (haven't checked if it is passed as a param or in the text string)
.set('lastlogin', 'NOW()', { dontQuote: true })
Soo I changed it to GETTIME() and mssql failed. squel was generating 
set lastlogin = @p1 
and putting GETTIME() into the param array which failed when I called ps.prepare which is reasonable. 
Soo I checked on here and it was mentioned to use squel.str in .set('lastlogin', squel.str("GETDATE()"), { dontQuote: true }) and that failed too. Then I noticed that v5 was mentioned and I was using v4 so I upgraded to v5 and that was working. I think the dontQuote is irrelevant here so will try without.
But then the  rest of my app keeled over.
What I am doing there is setting up a complicated join query at the beginning and that is still working fine
var sq = squel.select({}).lots of things here 
                      .where("t.status <> 'D'")
                      .order('t.tdate');
then 
var swhere = squel.expr();
for (i in p){ // p contains lots of possible params or none
    switch(p[I]){
        if any of the possible params are passed into my app I add them to the swhere like so
        'size': swhere.and('b.' + i + ' = ?', p[i]); break;
    }
}
then I pass my built up query back like so
sq.where(swhere).toParam()
This is where the problem is. If swhere hasn't been added to I get a spurious AND ()
"SELECT TOP (25) "u"."avatar", "u"."description" .... WHERE (t.status <> 'D') **AND ()  ** ORDER BY t.tdate ASC"
Trying to track down where this was coming from I inspected 
sq.where(swhere).toParam() in the debugger a few times and each  time it added another spurious AND ()
.... WHERE (t.status <> 'D') AND () AND () AND () ORDER BY t.tdate ASC"
Now I could set a flag to say if the swhere clause has been added to and not use it but that doesn't seem right. An empty where expression shouldn't add an empty AND.

Sorry if that isn't clear it is a bit late here :)

**Comment by hiddentao** [comment]
Sorry, the formatting in the description makes it hard to read. Would you be able to give me the simplest code possible which reproduces the issue you're talking about (i.e. empty AND)?

**Comment by ZeusIV** [comment]
Hi Hiddenatao,
Sorry if it wasn't clear. I don't know if I can pare this down any more but it does show the error.

//////////////////////////////////////////////////////////////////////////////////////
var p = { }; // 
//var p = { 'quantity': 6 }; // uncomment as needed


var squel = require('squel').useFlavour('mssql');
var EL = { colnames: "adate,tdate,id,t,auth,username,craft,item,size,quantity,price,currency,text,image,server,times".split(',') }
var sq = squel.select({
	autoQuoteFieldNames: true, autoQuoteTableNames: false
	, replaceSingleQuotes: true, nameQuoteCharacter: '"', tableAliasQuoteCharacter: '"'
	, numberedParameters: true, numberedParametersPrefix: '@p'
})
                .fields(['u.avatar', 'u.description'])
                .fields(EL.colnames.join(",t.").split(','))
                .field('b.bid')
                .from('trades', 't')
                .left_join('users', 'u', 't.username = u.username')
                .left_join(
	squel.select()
                                .field('max(bid)', 'bid').field('tradeid').from('bids').group('tradeid')
                                , 'b', 't.id = b.tradeid'
)
                .where("t.status <> 'D'")
                .order('t.tdate');
var swhere = squel.expr();

for (i in p) {
	switch (i) {
		case 'quantity':
			if (true) {
				console.log('adding and');
				swhere.and('t.quantity = ?', p[i]);
			}
	}
}
console.log(sq.where(swhere).toParam().text);
console.log(sq.where(swhere).toParam().text);
console.log(sq.where(swhere).toParam().text);
///////////////////////////////////////////////////////////////////////////////////////////////////////////////
The variable EL.colnames contains the  columns that can be added to the where in the switch statement but  just one will do to show the error. p contains the column value pairs. If p is empty I get an empty AND (). If p = { 'quantity': 6 }; it adds AND ("t"."quantity" = @p1)
I don't call sq.where(swhere).toParam().text more than once in my prog but when it is called more than once it adds AND () AND () AND () or AND ("t"."quantity" = @p1) AND ("t"."quantity" = @p1) AND ("t"."quantity" = @p1)
I don't recall it doing that in v4 but anyway the problem is the empty AND (). Why is it an AND not an OR as a .expr() can hold either.

Regards
Z

**Comment by hiddentao** [comment]
Thanks! Fixed in 5.0.2
