### ISSUE TITLE
Change the definition from anonymous function to standard class definition

### ISSUE THREAD

**Issue by Exlord** [hiddentao/squel#228]
HI, this package seems very nice, but it would be much better if it you change the definition from anonymous function to standard class definition so that IDE's could detect the type and provide intelligence/autocompletes .

And also the `modules.exports` part should be changed too.

My suggestion would be to completely drop the browser support and focus on node and avoid anonymous functions or at least provide jsdoc comments so that IDE can detect the types and provide intelligence/autocompletes.

**Comment by racekarl** [comment]
I disagree with respect to browser support.  This library is very useful in hybrid mobile apps (e.g. cordova/phonegap) for accessing the device's sqlite database.

**Comment by hiddentao** [comment]
I think jsdoc comments are the way forward. Until very recently squel wad written in CoffeeScript which is why this hadn't been done. Actually there is decent documentation within the code, it's just not in the jsdoc format.
