### ISSUE TITLE
Too much parenthesis in insert select query

### ISSUE THREAD

**Issue by yoleth** [hiddentao/squel#231]
Hi,

When doing an insert select request, there is too much parenthesis in result :

`squel.insert().into("students").fromQuery(
            ['username'],
            squel.select().field('name').from('candidates')
        ).toString()
`

Has as result :

`INSERT INTO students (username) ((SELECT name FROM candidates))` 

Instead of 

`INSERT INTO students (username) (SELECT name FROM candidates)`

**Comment by hiddentao** [comment]
This is an unfortunate side effect of the v5 re-architecture. Does this cause querying problems for you?

**Comment by yoleth** [comment]
Yes, a syntax error with mysql database :

`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(SELECT name FROM candidates))' at line 1`

**Comment by hiddentao** [comment]
Fixed in 5.1.0
