### ISSUE TITLE
Delete from multitables does not work

### ISSUE THREAD

**Issue by yoleth** [hiddentao/squel#233]
Hi,

When I try to delete from two tables in same time I've got an error. Here is my request :

`squel.delete()
        .from("students", "s")
        .outer_join("marks", "m", "m.student_id = s.id")
        .toString()`

The result is :

`DELETE FROM students `s` OUTER JOIN marks `m` ON (m.student_id = s.id)`

Instead of 

`DELETE s, m FROM students `s` OUTER JOIN marks `m` ON (m.student_id = s.id)`

Which leads to an error :

`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`s` OUTER JOIN marks `m` ON (m.student_id = s.id)' at line `

Thanks

**Comment by hiddentao** [comment]
Fixed in 5.1.0.

```js
squel.delete().target('s').target('m').from("students", "s") .outer_join("marks", "m", "m.student_id = s.id") .toString()
```
