### ISSUE TITLE
Version 5.1.0 breaks multiple subqueries in setFieldsRows

### ISSUE THREAD

**Issue by imsnif** [hiddentao/squel#235]
The following code:
```javascript
const squel = require('squel')

const subQuery1 = squel.select()
  .from("my_other_table")
  .where("Attr LIKE 'value'")

const subQuery2 = squel.select()
  .from("yet_another_table")
  .where("Attr LIKE 'value'")

const sql = squel.insert()
  .into("my_table")
  .setFieldsRows([
    {value: subQuery1, OtherValue: subQuery2},
    {value: subQuery1, OtherValue: subQuery2}
  ])

console.log(sql.toString())
```
In version 5.0.4 produces:
`INSERT INTO my_table (value, OtherValue) VALUES ((SELECT * FROM my_other_table WHERE (Attr LIKE 'value')), (SELECT * FROM yet_another_table WHERE (Attr LIKE 'value'))), ((SELECT * FROM my_other_table WHERE (Attr LIKE 'value')), (SELECT * FROM yet_another_table WHERE (Attr LIKE 'value')))`

In version 5.1.0 produces:
`INSERT INTO my_table (value, OtherValue) VALUES (SELECT * FROM my_other_table WHERE (Attr LIKE 'value')), (SELECT * FROM yet_another_table WHERE (Attr LIKE 'value'))), ((SELECT * FROM my_other_table WHERE (Attr LIKE 'value')), (SELECT * FROM yet_another_table WHERE (Attr LIKE 'value'))`

(The difference is the leading paren and closing paren right after VALUES and right at the end).
The first is a valid query, the second gives a syntax error.

Looking briefly at the code, this seems to have been caused by:
https://github.com/hiddentao/squel/commit/b8cc37d3679a6328c10bdf36c100776c482faab3

**Comment by hiddentao** [comment]
Thanks, fixed in 5.1.1
