### ISSUE TITLE
How to selectively disable quoting of certain field names ?

### ISSUE THREAD

**Issue by mandeepm91** [hiddentao/squel#240]
I am trying squel.js for building queries with postgres database. We have a table with the name "user" which is a reserved keyword in postgres.

Currently I am trying this config for all queries

      var squel = require('squel').useFlavour('postgres');
      var query =  squel.select({ 
        autoQuoteFieldNames: true,
        autoQuoteTableNames: true,
        nameQuoteCharacter: '"',
        tableAliasQuoteCharacter: '"',
        fieldAliasQuoteCharacter: '"'
       })

This escapes all the table names and column names so that we do not face issue of collision with a reserved keyword name like "user". However, it also escapes function calls like `.field("row_to_json(u)")` become `"row_to_json(u)"`

And it causes error 

    Unhandled rejection error: column "row_to_json(u)" does not exist

Any idea how can I selectively disable escaping for certain fields or disable escaping for functions in a generic way if possible ?

**Comment by hiddentao** [comment]
Try `.field(squel.str('row_to_json(u)'))` instead.

**Comment by mandeepm91** [comment]
Thanks! It works perfectly fine. But is this the ideal way of doing this ?

**Comment by hiddentao** [comment]
Yes this is the way.


On 3 June 2016 at 18:53:53, Mandeep SIngh Gulati (notifications@github.com) wrote:

Thanks! It works perfectly fine. But is this the ideal way of doing this ?
