### ISSUE TITLE
Support for PostgreSQL DISTINCT ON

### ISSUE THREAD

**Issue by saltire** [hiddentao/squel#249]
Squel supports SELECT DISTINCT through the select().distinct() function, but it would be nice if it also supported Postgres' SELECT DISTINCT ON (expr1, expr2) syntax.

https://www.postgresql.org/docs/current/static/sql-select.html#SQL-DISTINCT

**Comment by hiddentao** [comment]
A PR is welcome.

**Comment by hiddentao** [comment]
Done on #252, #253
