### ISSUE TITLE
Replace statement

### ISSUE THREAD

**Issue by hleon12** [hiddentao/squel#251]
Add native support to REPLACE statement. It could be handy without write a custom query.

More info: [http://dev.mysql.com/doc/refman/5.7/en/replace.html]( )

**Comment by hiddentao** [comment]
Is this MySQL only? a PR is wecome.

**Comment by hleon12** [comment]
Yes. I created a [PR](https://github.com/hiddentao/squel/pull/254). Currently, I'm using this change in other projects.
