### ISSUE TITLE
Where function doesn't work with an Expression generated by a different instance of Squel.js

### ISSUE THREAD

**Issue by nick1n** [hiddentao/squel#255]
We have multiple modules that use the squel module and we use PostgreSQL so I would like to use the useFlavour function but it doesn't work when different modules that interact with each other do `var squel = require('squel').useFlavour('postgres');`

We have one module that builds the SELECT query and it calls another module that builds the WHERE expression and this is where I'm seeing this issue, the returned expression was generated with a different instance of squel then the caller module's squel instance due to useFlavour making a new instance of squel for each module.

The workaround is just not use useFlavour and manually overwrite the Query Builder Options for PostgreSQL on each new query and everything works.

If this isn't the correct way of doing something like this, that's fine, just wanted to put this out there to maybe help someone if they run across this same issue.

I wrote a simple test to duplicate the results that I'm seeing:

``` js
// expr.js
var squel = require('squel').useFlavour('postgres');

module.exports = function() {
    return squel.expr().and('1 = 1');
};
```

``` js
// test.js
var squel = require('squel').useFlavour('postgres');
var expr = require('./expr.js');

squel.select().from('test', 't').where(expr());
```

Here is the error:

```
/.../node_modules/squel/dist/squel.js:373
            throw new Error("expression must be a string or Expression instance");
            ^

Error: expression must be a string or Expression instance
    at _class22._sanitizeExpression (/.../node_modules/squel/dist/squel.js:373:19)
    at _class22._condition (/.../node_modules/squel/dist/squel.js:2102:26)
    at _class22.where (/.../node_modules/squel/dist/squel.js:2187:25)
    at _class49._this32.(anonymous function) [as where] (/.../node_modules/squel/dist/squel.js:2690:27)
    at Object.<anonymous> (/.../test.js:5:57)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
```

Another very simple test to get the same error:

``` js
var squel = require('squel');

squel.useFlavour('postgres').select().from('test', 't').where(squel.useFlavour('postgres').expr().and('1 = 1'));
```

Tested with:
Node v5.1.0 and v6.3.0
Squel.js v5.3.3

**Comment by hiddentao** [comment]
This reminds me of #229. Because Squel uses `instanceof` checks within its logic and because use a flavour essentially involves rebuilding a flavour-specific version of Squel you get the error you're seeing.

I think perhaps it's time to revisit this general issue and fix it.
