### ISSUE TITLE
Set Buffer to MySQL BLOB field

### ISSUE THREAD

**Issue by Smert** [hiddentao/squel#272]
```javascript
function updateFile(id, file) {
  // file - <Buffer 01 ac 02 bc 52 ec 39 ... >
  squel.update().table('test').set('file', file).where('id = ?', id);
}
```

Returns:

> field value must be a string, number, boolean, null or one of the registered custom value types

**Comment by hiddentao** [comment]
I'm not sure how Blob data is to be passed to the MySQL but in any case you can use a custom value handler for this, see https://hiddentao.com/squel/#custom_formatting

**Comment by Smert** [comment]
BLOB data doesn't require transformation to string in MySQL driver
http://stackoverflow.com/questions/25951251/nodejs-mysql-insert-blob

**Comment by Smert** [comment]
squel.registerValueHandler(Buffer, buffer => buffer);

Its must be by default

**Comment by hiddentao** [comment]
@Smert Sorry, don't understand your comment. Please clarify.

**Comment by SeregPie** [comment]
Add this line somewhere in your project. This will convert all ``Buffer` instances to hex code.

```js

squel.registerValueHandler(Buffer, buffer => '0x'+buffer.toString('hex'));

```

**Comment by Smert** [comment]
@SeregPie It will be work fine. But `toString()` is unnecessary conversion of type. mysql driver could work with Buffer type directly
