### ISSUE TITLE
Multiple columns in returning()

### ISSUE THREAD

**Issue by jbrawnjr** [hiddentao/squel#278]
I was trying to do something like the following:

``` javascript
squel.insert().into('my_table')
  // ...
  .returning('id')
  .returning('created');
```

But it would appear that Squel only stores a single value for `returning()`, so whichever value it was most recently called with is the only one that ends up in the query. This is in contrast to other methods, like `field()`, where successive calls add to an internal list.

It is valid in PostgreSQL to return multiple values as in the above. What is the best way to accomplish this in Squel?

**Comment by hiddentao** [comment]
You could implement your own returning Block and then replace the insert query construction call with one which uses your custom block.
