### ISSUE TITLE
Expression bracket handling buggy, or misunderstanding on my end? 

### ISSUE THREAD

**Issue by rj33** [hiddentao/squel#285]
I have this expression:
squel.expr().and(squel.expr().and(squel.expr().and('A').and('B')).or(squel.expr().and('C').and('D'))).and('E').toString();

Which on 5.5.0 produces:
(A AND B) OR (C AND D) AND E

But I was hoping for:

((A AND B) OR (C AND D)) AND E

Due to AND taking precedence in SQL, the first statement is equivalent to:

(A AND B) OR ((C AND D) AND E)

Rather than the form I was expecting.

Is this a bug with the expressions and bracket cleaning, or am I building the expression incorrectly?

**Comment by hiddentao** [comment]
Ah that's a good spot. So squel doesn't care about operator precedence - the expression builder isn't designed to take that into account, it's really just a convenience API for buildings long expression strings. So you will still need to handle that yourself.

**Comment by rj33** [comment]
That's a pity, as it makes the expression builder a lot less useful if you have to add your own brackets all over the place. The actual expression builder nesting itself implies a precedence disambiguation that seems to be lost during final production. Just making sure each sub-expression is bracketed would seem to avoid a lot of accidental expression precedence issues. I'm sure I'm not the only one who would assume that the bracketing used in the builder expression:
squel.expr().and(squel.expr().and(squel.expr().and('A').and('B')).or(squel.expr().and('C').and('D'))).and('E')

would be preserved. 

At the moment I'm needing to do things like "("+expr.toString()+")" in a bunch of places, but it seems it wouldn't be that hard for the expression builder to make sure each expression was self contained in brackets. I guess the final output might be uglier , but it would be less likely to fail in subtle ways when the final output ends up being bracketed differently than the original expression structure suggests it would.

**Comment by rj33** [comment]
Another thought on this, I do wonder why the code is able to bracket squel.expr().and('A').and('B')
as (A AND B), but then:
squel.expr().and(squel.expr().and('A').and('B')).or(squel.expr().and('C').and('D'))).and('E')
doesn't add the brackets around the surrounding AND, which on the surface seems like the same operation). What leads to the suppression to the second level of brackets? It would seem something is making the explicit choice to avoid surrounding brackets in some situations but not others?

**Comment by hiddentao** [comment]
Am going to close this since #286 deals with it.
