### ISSUE TITLE
_applyNestingFormatting(str) breaks expression builder nesting

### ISSUE THREAD

**Issue by rj33** [hiddentao/squel#286]
Sorry to raise this again, I mentioned this issue here:
https://github.com/hiddentao/squel/issues/285
,  but I might not have been clear on describing the issue. After looking at the sequel.js code to see what is causing the problem described, I'm fairly sure this is an unintended bug in the expression builder brought about by bracket removal in the _applyNestingFormatting function.

A quick summary of the issue previously posted:

squel.expr().and(squel.expr().and(squel.expr().and('A').and('B')).or(squel.expr().and('C').and('D'))).and('E').toString();

If it was preserving the nesting of the original expression should output:
((A AND B) OR (C AND D)) AND E

Instead it outputs:
(A AND B) OR (C AND D) AND E

Ignoring the nesting of the (A AND B) OR (C AND D) expression by removal the brackets around it. As previously mentioned these are two different logical expression in SQL and return different results.

The reason the brackets are not output is because of this:

```
    _applyNestingFormatting(str, nesting = true) {
      if (str && typeof str === 'string' && nesting) {
        // don't want to apply twice
        if ('(' !== str.charAt(0) || ')' !== str.charAt(str.length - 1)) {
          return `(${str})`;
        }
      }

      return str;
    }
```

That code is essentially accidentally unnesting expressions that should be nested. It seems to be trying to avoid cases like:
(A and B)
turning into
((A and B))

Which it does a good job of , but when you have
(A AND B) OR (C AND D)

The fact that it gets a hit on 'starts with a bracket, ends with a bracket', so doesn't add a bracket as it thinks it is already nested appears to be incorrect behaviour. Here, the start and end brackets here are for closing internal expressions, they do not enclose the entire expression which is what the test is trying to detect.

This s preventing the correct nesting being output, because (A AND B) OR (C AND D) is now deemed to be already nested in brackets (which it clearly isn't), so the final output of the expression above is the incorrect:

(A AND B) OR (C AND D) AND E

instead of the correct (based on the original nesting of the expression builder):

((A AND B) OR (C AND D)) AND E

Changing
```
        if ('(' !== str.charAt(0) || ')' !== str.charAt(str.length - 1)) {
          return `(${str})`;
        }
```

to simply

```
return `(${str})`;
```

fixes the nesting problem for my test case. I imagine you'll have cases where you get extra enclosing brackets if you make that change, but the extra brackets are at least safe, incorrectly removing them on false positives for the "already wrapped in brackets" test is not safe, and given it appears to be used in places other than expression builder, may break other types of testing that has structures where the expression already starts and ends with a bracket, but they are not enclosing brackets. 

It is possible to correctly detect 'already wrapped by brackets' by traversing the string and counting open and closes and their positions, and checking if the last close is both at the end of the string, and closing an open that started at the start of the string, but I doubt it is worth the effort, and it might be easier and safer to just avoid trying to clean up double bracketing.

To make it clear how serious this issue is, imagine you've built the expression above (very reasonably given the syntax of the builder) expecting this:

DELETE FROM table WHERE ((A AND B) OR (C AND D)) AND E

but get this:
DELETE FROM table WHERE (A AND B) OR (C AND D) AND E

You've just deleted a bunch more rows that the nesting of your expression builder statement suggested you would, because the latter is interpreted as the much wider:
DELETE FROM table WHERE (A AND B) OR ((C AND D) AND E)

So previously E needed to be true to delete rows , but now you can delete rows if E is false, as long as (A AND B) is true. 

I realise from your last reply, that you don't want to deal with operator precedence issues, which is completely sensible,  but that is exactly why you need to get the bracketing right in order to preserve the nesting of the original expression builder statement. That allows the user to nest statements in the builder such that precedence isn't an issue. Lifting statements up nesting levels which is what the incorrect bracket removal is doing means you are transforming the nesting logic in a way that precedence can impact the final result.

I hope this gives a better explanation of why I think this is a bug rather than just unsupported precedence handling. tl;dr version is that the code is currently unnesting structures in ways that change their interpretation from the originally supplied structure, and will execute sql logic the user didn't think they were producing due to the nesting changes.

**Comment by hiddentao** [comment]
Thanks for the thorough investigation. I am going first investigate whether I can come up with a smarter nesting bracketing solution...

**Comment by hiddentao** [comment]
Ok, I've implemented a fix inside the `_applyNestingFormatting` method. It now makes a more thorough check to ensure that the string sent in is actually nested. Basically, before it was falsely concluding that `(x)...(y)` was nested because it starts with `(` and ends with `)`. It now handles that case better.

Fix is in 5.6.0.

**Comment by rj33** [comment]
Thanks, looks like a good fix! 

Thanks also for all your great work on this library. Not having to build sql strings directly with a bunch of string concatenation has saved many hours of bug fixing complicated sql statements that I am sure I would have otherwise been spending.

**Comment by hiddentao** [comment]
You're more than welcome, and thanks for taking the time to investigate this.
