### ISSUE TITLE
.onConflict is not a function?

### ISSUE THREAD

**Issue by toddmedema** [hiddentao/squel#290]
Trying to run

```
let query = Squel.insert()
      .into(table)
      .setFields(object)
      .onConflict('id', object);
```

Results in this error:
`TypeError: Squel.insert(...).into(...).setFields(...).onConflict is not a function`

Node v6.9.2
Squel 5.5.0

All other Squel commands I'm running are without issue, such as 
```
let query = Squel.insert()
      .into(table)
      .setFields(object);
```

**Comment by wiogit** [comment]
The method `onConflict()` is specified as being only in the postgres flavor.
You need to call `Squel = Squel.useFlavour('postgres');` if you want access use it.

**Comment by toddmedema** [comment]
Ah! That's it, thank you :)
