### ISSUE TITLE
Formatted Values get wrapped in Brackets

### ISSUE THREAD

**Issue by jay-ouellette** [hiddentao/squel#292]
`squel.registerValueHandler(typeof null, function (x) {return 'DEFAULT'})`

This produces "(DEFAULT)" not "DEFAULT"

The nestedBuilder option is set to false, so this should not happen

**Comment by hiddentao** [comment]
What's the full query?

**Comment by munir131** [comment]
@hiddentao I think it is introduced in 5.3
`let quey = squel.select().from('table').where('(x,y) in (?)', ['(100,100)', '(200,200)']).toParam();` 
in 5.2 output was:
select * from table where (x,y) in ((100,200),(200,200));
but after 5.3 it is
select * from table where (x,y) in (((100,200),(200,200)));

**Comment by hiddentao** [comment]
@munir131 Why not do `squel.select().from('table').where('(x,y) in ?', ['(100,100)', '(200,200)']).toParam()` ?

**Comment by munir131** [comment]
@hiddentao I did `squel.select().from('table').where('(x,y) in ?', ['(100,100)', '(200,200)']).toParam()`. But point is `squel.select().from('table').where('(x,y) in ?', ['(100,100)', '(200,200)']).toParam()` was not giving expected query before 5.3
It was breaking changes or bug.

**Comment by hiddentao** [comment]
@munir131 Ok I get ya. Then nesting logic has changed over the last few iterations to give the end-user more control over when nesting takes place. But I think the custom value handler needs a bit more power - will do a fix now.

**Comment by hiddentao** [comment]
In 5.9.0 you can now prevent the automatic nesting of value handler return values by doing:

```js
squel.registerValueHandler(typeof null, function (x) {
  return { rawNesting: true, value: 'DEFAULT' }
})
```

**Comment by munir131** [comment]
@hiddentao Great. I think we can close this issue then.
