### ISSUE TITLE
`isSquel` function to check if the given param is a squel object

### ISSUE THREAD

**Issue by ravenjohn** [hiddentao/squel#297]
I'm creating a custom mysql library and I want to detect if the given object is from squel. If it is, I will call `toParam()` then properly use `.text` and `.values` to execute the query.

**Comment by hiddentao** [comment]
There is an internal method called `_isSquelBuilder`, see https://github.com/hiddentao/squel/blob/master/src/core.js#L115

Perhaps I should make this public

**Comment by ravenjohn** [comment]
thanks! I will just use that for now.

```js
const query = squel.select()
    .from('table')
    .field('field1');

squel.cls._isSquelBuilder(query); // true
```

**Comment by hiddentao** [comment]
Note that this is now `isSquelBuilder()` in 5.8.0 onwards.
