### ISSUE TITLE
5.7.0 changes output of .returning() when using autoQuoteFieldNames

### ISSUE THREAD

**Issue by makkeu** [hiddentao/squel#298]
If using autoQuoteFieldNames, .returning() provides invalid sql output.
Is my syntax for returning multiple fields correct? Documentation is unclear on this.

Code:
```
var squel = require('squel').useFlavour('postgres');
squel.update({autoQuoteFieldNames: true, nameQuoteCharacter: '"'})
.table('table')
.setFields({testField: 1, field: 2})
.returning('id, "testField"').toString();
```

5.6.0 result:
```
'UPDATE table SET "testField" = 1, "field" = 2 RETURNING id, "testField"' // valid sql
```

5.7.0 result:
```
'UPDATE table SET "testField" = 1, "field" = 2 RETURNING "id, "testField""' // invalid sql
```

**Comment by hiddentao** [comment]
You can now specify multiple returning fields, e.g.:

```js
squel.update({autoQuoteFieldNames: true, nameQuoteCharacter: '"'})
.table('table')
.setFields({testField: 1, field: 2})
.returning('id)
.returning('testField')
.toString();
```

Does this work?

**Comment by shadrech** [comment]
This is not working for me @hiddentao . I get this error:
`TypeError: squel.insert(...).into(...).setFields(...).returning is not a function`

**Comment by makkeu** [comment]
Sorry, I have forgot to answer this. Yes, using multiple returning fields like that fixes the issue. Thanks, this can be closed.
