### ISSUE TITLE
How to extend existing query builders with an additional block

### ISSUE THREAD

**Issue by deinspanjer** [hiddentao/squel#300]
I've read through the guide and API docs, but I haven't seen a clean way of doing this.

If I wanted to add for instance a WINDOW block to the Select query builder, or add my own special variant of toString() or toParam() that could be used anywhere within a valid query builder instance, is there a way to do that by extending an existing query builder object defined in core or in a flavour rather than completely redefining each of the primary builders (select, update, insert, delete) the way the flavours do it?  If I just copy and paste the definition of a query builder, I'm afraid I might either introduce a transcription error, or down the line, miss some new functionality added to one of the base builders because I'm off in my own forked definition.

Additional context regarding adding a new method, I'm working with squel inside PostgreSQL plv8 using the node-plv8 mechanism that lets you add node modules to be used inside plv8.

Currently, after I've built a SQL command such as:
`let sql = squel.select().from(squel.str("generate_series(?,?,?)",1,10,2)).toParam()`

I then have to execute it by doing something like:
`let results = plv8.execute(sql.text, sql.values);`

I was hoping to be able to add a new method called execute() to the builder such that I could instead just call:
`let results =  squel.select().from(squel.str("generate_series(?,?,?)",1,10,2)).execute();`

And that execute function would basically do the work for me:
```
  squel.<QueryBuilder>.execute = function() {
  let obj = this.toParam();
  return plv8.execute(obj.text, obj.values);
}
```

**Comment by hiddentao** [comment]
So what you want is an ExecuteBlock or something like that which extends `squel.cls.Block`. This block would expose an `execute()` method. You then need to add this block to the query builders. You can do this by - as you say - completely overriding the builder constructor. Or you could simply override the convenience methods. If you look in the code:

```js
  let _squel = {
    select: function(options, blocks) {
      return new cls.Select(options, blocks);
    },
    update: function(options, blocks) {
      return new cls.Update(options, blocks);
    },
...
```

So just override `squel.select()` with your own function that initializes it with the blocks you desire. I admit that at the moment there's no easy way to just "append" a new block to the existing list.

**Comment by deinspanjer** [comment]
Okay.  Thanks for the tip!  I might see if I can get a reference to the list of blocks in the "old" select and then just append my one block to that one when I new it up in my replacement convenience method.
