### ISSUE TITLE
Unable to add a parameterized table function to a Squel builder

### ISSUE THREAD

**Issue by deinspanjer** [hiddentao/squel#301]
I was trying to use squel to build the following PostgreSQL query:
`select * from generate_series(1,10,2) tblfn(odds)`

I can do it if I inline the values:
`squel.select().from("generate_series(1,10,2)","tblfn(odds)").toParam()`

But I can't find a way to get it to work with parameters.
The .from() block doesn't accept params, only an alias.
If I give the .from() block a squel.str(), then it puts an extra level of parenthesis in the query which is not syntactically valid:
```
squel.select().from(squel.str("generate_series(?,?,?)",1,10,2),"tblfn(odds)").toParam()
// gives the following:
{"text":"SELECT * FROM (generate_series($1,$2,$3)) AS tblfn(odds)","values":[1,10,2]}
// and postgres throws the following error:
[2017-02-26 13:05:34] [XX000] ERROR: syntax error at or near ")"
```

Is there an alternate way to be able to get those function values into the query as parameters?

**Comment by hiddentao** [comment]
I've just released 5.8.0 with the new `rstr()` function, see https://hiddentao.com/squel/api.html#cls_rstr

You can now do this to get what you want:

```js
squel.select().from(squel.rstr("generate_series(?,?,?)",1,10,2),"tblfn(odds)").toParam()
```

**Comment by deinspanjer** [comment]
Wow, thanks so much for the feature! I will try this out right away.

**Comment by deinspanjer** [comment]
This is working great.
