### ISSUE TITLE
Nesting CTEs instead of combining them as siblings

### ISSUE THREAD

**Issue by deinspanjer** [hiddentao/squel#303]
Currently, Squel will let you define multiple .with() blocks after a .select() and they will all be emitted after the WITH keyword using a comma separator.

Sometimes however, you want to do the following:
```
WITH hello_world AS (
  WITH hello AS (
    SELECT 'hello' AS first
  ), world AS (
    SELECT 'world' AS second
  )
  SELECT concat(first, ' ', second) AS greeting
  FROM hello,world
)
SELECT greeting
FROM hello_world
;
```

**Comment by deinspanjer** [comment]
I realize this particular example could be rewritten without the nesting, but hopefully it just explains the needed syntax.

**Comment by hiddentao** [comment]
So we'd just need to modify the WITH block to support query builders and nested query builders

**Comment by deinspanjer** [comment]
Nevermind!  This is actually possible:
```
sql.select({separator:"\n"})
.with("hello_world",
  sql.select({separator:"\n"})
  .with("hello",
    sql.select({separator:"\n"})
    .function("'hello'","first"))
  .with("world",
    sql.select({separator:"\n"})
    .function("'world'","second"))
  .function("concat(first,' ',second)","greeting")
  .from("first")
  .from("second"))
.field("greeting")
.from("hello_world")
.toParam();
```

I got confused when I first tried to do this because of the inversion of the sql.select() before the sql.with().
