### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by jy95** [hiddentao/squel#304]
I read this : https://hiddentao.com/squel/api.html#select_distinct

So why this ? I have seen in your examples : 

```js
log(
    squel.select()
        .from("students")
        .field("id")
        .distinct()
        .toString()
);
/*  SELECT DISTINCT id FROM students    */
``
`PS: You can close this issue.

However, the documentation is a little unclear about this. Maybe a clear explanation about it

**Comment by hiddentao** [comment]
The `fields...` parameter only applies to Postgres, see https://github.com/hiddentao/squel/blob/master/src/postgres.js#L153
