### ISSUE TITLE
squel.cofee link broken

### ISSUE THREAD

**Issue by kplatter** [hiddentao/squel#313]
The link/documentation, squel.coffee is broken, I am guessing that we should just look in the code on github?  

Hopefully you can see that it is possible to totally override the built-in query building logic. Also notice that each building block within a query can have a different set of options applied to it. Check out **squel.coffee** to see the available building blocks.

**Comment by hiddentao** [comment]
Which link are you referring to?

**Comment by hiddentao** [comment]
This is now fixed, thanks.
