### ISSUE TITLE
.setFieldsRows(...).onDupUpdate is not a function

### ISSUE THREAD

**Issue by codekraft-studio** [hiddentao/squel#315]
Can you add make the method: __onDupUpdate__ concatenable even for the __setFieldsRows__ method?

I would like to build this query: 
```sql
INSERT INTO t (t.a, t.b, t.c)
VALUES ('key1','key2','value'), ('key1','key3','value2')
ON DUPLICATE KEY UPDATE
t.c = VALUES(t.c)
```
I would like to be able to do this:
```javascript
var query = squel.insert()
.into('t')
.setFieldsRows([...])
.onDupUpdate('t.c', 'VALUES(t.c)')
.toString();
```
But it fails with: __.setFieldsRows(...).onDupUpdate is not a function__, I tried to look at the code but I can't understand how it's working, I assume the __.setFieldsRows__ method should return the class instance to be able to concatenate other methods

I see that both cls.SetFieldBlock and cls.MysqlOnDuplicateKeyUpdateBlock extends cls.AbstractSetFieldBlock but with .setFields is working and with .setFieldsRows not.

Many thanks in advance and great tool, i'm using a lot in my projects.

**Comment by FerrielMelarpis** [comment]
@codekraft-studio 
> **.setFieldsRows(...).onDupUpdate is not a function**

I think the issue here is that you forgot to set the flavour of your squel.
You should have imported it like this:
```js
const squel = require('squel').useFlavour('mysql');
```

**Comment by codekraft-studio** [comment]
@FerrielMelarpis  great! many thanks!
