### ISSUE TITLE
test(baseclasses): fix assertion

### ISSUE THREAD

**Issue by blackwindforce** [hiddentao/squel#316]
**I'm submitting a ...**

- bug report

**Current behavior:**

[https://github.com/hiddentao/squel/blob/5.10.0/src/core.js#L2064](https://github.com/hiddentao/squel/blob/5.10.0/src/core.js#L2064)

```coffeescript
@inst.getBlock(squel.cls.FunctionBlock)
# => undefined
```

[https://github.com/hiddentao/squel/blob/5.10.0/test/baseclasses.test.coffee#L1216](https://github.com/hiddentao/squel/blob/5.10.0/test/baseclasses.test.coffee#L1216)

```coffeescript
'invalid': ->
    assert.throws (-> @inst.getBlock(squel.cls.FunctionBlock) )
```

**Expected / new behavior:**

```coffeescript
@inst.getBlock(squel.cls.FunctionBlock)
# => throws an error
```

or

```coffeescript
'invalid': ->
    assert.same @inst.getBlock(squel.cls.FunctionBlock), undefined
```

**Comment by blackwindforce** [comment]
Hi,

I found a [bug](https://github.com/hiddentao/squel/blob/5.9.1/test/baseclasses.test.coffee#L816) in your test case, it would be great to schedule and fix it.

Thank you.

**Comment by blackwindforce** [comment]
Hi,

I found a [bug](https://github.com/hiddentao/squel/blob/5.9.1/test/baseclasses.test.coffee#L866) in your test case, it would be great to schedule and fix it.

Thank you.

**Comment by blackwindforce** [comment]
Hi,

I found a [bug](https://github.com/hiddentao/squel/blob/5.9.1/test/baseclasses.test.coffee#L913) in your test case, it would be great to schedule and fix it.

Thank you.

**Comment by hiddentao** [comment]
I'm not entirely clear on the problems here - is is the string quores? Please raise PRs for issues.

**Comment by blackwindforce** [comment]
**I'm submitting a ...**

- bug report

**Current behavior:**

[https://github.com/hiddentao/squel/blob/5.10.0/test/baseclasses.test.coffee#L711](https://github.com/hiddentao/squel/blob/5.10.0/test/baseclasses.test.coffee#L711)

```coffeescript
'default': ->
    escapedValue = undefined
    test.mocker.stub @inst, '_escapeValue', (str) -> escapedValue or str

    assert.same "'test'", @inst._formatValueForQueryString('test')

    assert.same "'test'", @inst._formatValueForQueryString('test')
    assert.ok @inst._escapeValue.calledWithExactly('test')
    escapedValue = 'blah'
    assert.same "'blah'", @inst._formatValueForQueryString('test')
```

**Expected / new behavior:**

```coffeescript
'default': ->
    escapedValue = undefined
    test.mocker.stub @inst, '_escapeValue', (str) -> escapedValue or str

    assert.same "'test'", @inst._formatValueForQueryString('test')

    assert.ok @inst._escapeValue.calledWithExactly('test')
    escapedValue = 'blah'
    assert.same "'blah'", @inst._formatValueForQueryString('test')
```

**Comment by blackwindforce** [comment]
@hiddentao I've updated previous 4 bug reports and also added a new one, please review and verify them. Looks like `chai.assert.deepEqual` is buggy, it would be great to find a new way and verify the test cases. And I apologize for unclear bug reports at beginning.

**Comment by hiddentao** [comment]
No problem, thanks for the report. These are now fixed.

`assert.deepEqual` was fine, what was happening was that some test keys were mistakenly written as functions, e.g:

```js
'separator': ->
  'parameterized': ->
    ...
  'non-parameterized': ->
    ...
```

should be:

```js
'separator':
  'parameterized': ->
    ...
  'non-parameterized': ->
    ...
```
