### ISSUE TITLE
`stringFormatter` defaults not applied

### ISSUE THREAD

**Issue by juneidysoo** [hiddentao/squel#320]
Hey there!

I am wondering if the `stringFormatter` is purposefully omitted from builder's default?

It seems that `BaseBuilder`'s constructor `JSON.parse(JSON.stringify())` is removing `stringFormatter` function defined in my custom flavour.

Thank you in advance. :)

**Comment by hiddentao** [comment]
I think perhaps it's due to it being `null` by default. Perhaps I can change it to not use JSON.parse.

**Comment by hiddentao** [comment]
Actually, no it's because JSON.parse(JSON.stringify()) can't handle functions.

**Comment by hiddentao** [comment]
Try 5.11.1 and let me know.

**Comment by juneidysoo** [comment]
> Actually, no it's because JSON.parse(JSON.stringify()) can't handle functions.

Yes, I was actually referring to that. And I thought that was intentional.

> Please try 5.11.1 and let me know.

Worked like a charm. Cheers
