### ISSUE TITLE
Where in: Operand should contain 2 column(s)

### ISSUE THREAD

**Issue by b4dnewz** [hiddentao/squel#332]
Hi, I've encountered this error: 
```
sqlMessage: "Operand should contain 2 column(s)"
```
while trying to do a query like this: 
```javascript
var data = [ [1, 2] ];
squel.delete()
.from('table')
.where('(field1, field2) IN ?', data)
.toString();

// Produces
DELETE FROM table WHERE ( (field1, field2) IN (1,2) )
```

I made a couple of tests and seems that the query built from squel is wrongly formed:
```
// Squel
DELETE FROM table WHERE ( (field1, field2) IN (1,2) )

// Expected
DELETE FROM table WHERE ( (field1, field2) IN ((1,2)) )  <-- note the subgrouping
```

It seems when the array contains only one item is not grouping it in the right way, instead when you use an array of multiple arrays it's working:
```javascript
var data = [ [1, 2], [3, 4] ];

squel.delete()
.from('table')
.where('(field1, field2) IN ?', data)
.toString();

// Produces
DELETE FROM table WHERE ((field1, field2) IN ((1,2), (3,4)))
```

I made a [plunker](https://plnkr.co/edit/GfqPf8LzSIdhdafVQTQo?p=preview) if you want to check this code above.

I didn't look at the source code yet, but if I can find where the problems come from I'll link it too.

__Update:__
By the way this can be solved simply by surrounding the question mark with parenthesis: `(?)` but I think the expected beheviour for an array is to be expanded like this:

```
// normal values doesn't get grouped
[ a ]  -> ( a )
[ a, b ]  -> ( a, b )

// arrays are grouped
[ [a] ]  -> ( (a) )
[ [a, b] ]  -> ( (a, b) )
[ [a, b], [c, d] ]  -> ( (a, b), (c, d) )

// example
array = [
[1, 2, 3],
[4, 5, 6]
];

// When preparing query
WHERE (field1, field2, field3) IN ?

// Expanded query
WHERE (field1, field2, field3) IN ( (?, ?, ?), (?, ?, ?) )

```
So if the value is an array (even just one) is grouped into parentesis.

**Comment by hiddentao** [comment]
I wasn't aware that this was how it arrays out to be expanded. My feeling is that since adding parantheses makes this work ok, users should just do that since it seems simple enough. As otherwise, squel would need more logic to check when/how an array value is being included within the query - and the logic is already tricky.

**Comment by b4dnewz** [comment]
I see your point and it's right.
But it will be great to introduce it in future, I'll try to contribute, but as you said the logic is already tricky and I had some trouble last time when I first attempted: :]
