### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by sm2017** [hiddentao/squel#337]
I want to use squel with react-native and have issue with https://github.com/hiddentao/squel/blob/master/dist/squel.js#L127

I use https://www.npmjs.com/package/es6-symbol polyfill

I add the following lines above `for`

```js
console.log('Symbol',Symbol);
console.log('Symbol.iterator',Symbol.iterator);
console.log('handlers[Symbol.iterator]',handlers[Symbol.iterator]);
```

the result is

```
'Symbol', [Function: Symbol]
'Symbol.iterator', {}
'handlers[Symbol.iterator]', undefined
```

**Comment by ankitbhatt511** [comment]
here is a little fix...
for react native

just do

npm install es5-ext

and make sure to import this library
like below 

require('es5-ext/array/#/@@iterator/implement');
const squel = require('squel').useFlavour('mysql');
