### ISSUE TITLE
"set" only when value is not undefined

### ISSUE THREAD

**Issue by ruifortes** [hiddentao/squel#41]
Sometimes I only have some field of the table I want to update.
I have to check each if a value is undefined and conditionally add the "set" clause.
Is there a way to instruct the "set" clause to only add to final string if value is not empty?
Eventually some configuration on how to handle empty string or null

**Comment by jinkim608** [comment]
I'd like to see this implemented to prevent cases like this:

>UPDATE users SET f_name = 'Jin', l_name = 'Kim', email WHERE (user_id='jk123');
