### ISSUE TITLE
800a01b6 problem: property or method unsopported

### ISSUE THREAD

**Issue by niconico49** [hiddentao/squel#52]
if i try to launch squelk inside a windows scriptng engine (wsh in this case by Wscript or Cscript) the engine give this error:
800a01b6 property or method unsopported
in this line:
return ((function() {
in the block QueryBuilder.prototype.toString

can you explain me some solution?

Thanks

**Comment by hiddentao** [comment]
Closing this, assuming it's no longer an issue.
