### ISSUE TITLE
Question: How to write SQL INSERT INTO SELECT Statement?

### ISSUE THREAD

**Issue by bobbylee** [hiddentao/squel#53]
I'm sure I'm not the only one but I can't find any documentation regarding this.
This SQL statement creates copies/duplicates.
How do I write SQL INSERT INTO SELECT Statement in Squel?

Example:
INSERT INTO table2
SELECT * FROM table1;

or

INSERT INTO table2
(column_name(s))
SELECT column_name(s)
FROM table1;

SQL Example taken from here:
http://www.w3schools.com/sql/sql_insert_into_select.asp

Squel insert() requires .set() and .set() requires 2 arguments which got me stuck.
Can this currently be converted from SQL to Squel?

Many Thanks

**Comment by pcothenet** [comment]
I would definitely be interested in that one (currently doing it manually (by appending my select to an insert string I create manually)

**Comment by hiddentao** [comment]
This is implemented in master, I just need to update the docs.

**Comment by pcothenet** [comment]
Awesome, let me know if I can help!

**Comment by SimeonC** [comment]
@hiddentao Nice work! Much more elegant than my current hack around! Can't wait to use it (and replace all my code...)

@pcothenet If you want a reference the relevant test is here: https://github.com/hiddentao/squel/blob/c5e6e136f25be5ffd7abe7ff184296f3603089fe/test/insert.test.coffee#L167-L177

**Comment by pcothenet** [comment]
Thanks! Will this be in 3.11.0?

**Comment by hiddentao** [comment]
Yes it will.

On 29/01/2015 13:45, Paul Cothenet wrote:
> Thanks! Will this be in 3.11.0?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hiddentao/squel/issues/53#issuecomment-71972301>.
> 

-- 
Ramesh Nair

Freelance Web Developer

www.hiddentao.com
www.github.com/hiddentao
