### ISSUE TITLE
EXISTS support...?

### ISSUE THREAD

**Issue by fdeandao** [hiddentao/squel#65]
Any suggestions how you would implement a EXISTS?.

i.e.

```
select id, course_file, status_package from publications_course c
 where exists(select 1 from configurations_courseinstance i where i.id=:idInstance and
 ((i.start_date is null and i.end_date is null)
 or (i.end_date is null and i.start_date <= now())
 or (i.start_date is null and i.end_date >= now())
 or (now() between i.start_date and end_date))
 and i.course_id=c.id and 
 exists(select 1 from configurations_userinstance where
 instance_id=i.id and exists(select 1 from                     
 academic_academicuser where id=student_id and username=:username)));
```

Regards

**Comment by hiddentao** [comment]
Am closing this due to lack of interest. I think the present solution (as outlined in the last comment) suffices.

**Comment by raddevon** [comment]
@hiddentao Sorry to resurrect after so long. If I want to use data from the user inside my `EXISTS` subquery, is there a way I can parameterize that and join it with the rest of my parameterized query to help me avoid injection attacks? (Not necessarily important to this question, but my `EXISTS` will be in a `.field()`.)

**Comment by hiddentao** [comment]
@raddevon Squel 5 has more flexible architecture which allows for unlimited parameterized query nesting, so with the latest squel (5.4.2) you should be able to do something like:

```js
squel.select()
  .from('table')
  .where('b = ?', 4)
  .where(squel.str('EXISTS(?)', squel.select().from('blah').where('a = ?', 5)))
.toParam()

/*
{ 
    text: "SELECT * FROM table WHERE (b = ?) AND (EXISTS((SELECT * FROM blah WHERE (a = ?))))", 
    values: [4,5]
*/

```
