### ISSUE TITLE
Is there a way to do a nested join?

### ISSUE THREAD

**Issue by ekbarber** [hiddentao/squel#68]
I see you can join to a sub query, but is there a way to do a nested join? 

For example, I'd like to create the following SQL

```
SELECT *
FROM
( 
   table1 t1 join table2 t2 on (t1.id = t2.id)
) join table 3 t3 on (t1.id = t3.id) 
```

I'm assuming that using the sub query, I would end up with something like:

```
SELECT *
FROM
( 
  SELECT * FROM table1 t1 join table2 t2 on (t1.id = t2.id)
) join table 3 t3 on (t1.id = t3.id) 
```

I'd much prefer doing it the first way if possible

**Comment by markdboyd** [comment]
I had a need to support nested joins on join blocks for a recent project, which is different than the example above. So for example:

``` sql
SELECT *
FROM table1 t1
LEFT JOIN table2 t2 
  INNER JOIN table3 t3 ON t2.id = t3.id
  ON t1.id = t2.id
```

I was able to create a basic implementation for doing so by extending the prototypes for join blocks to accept a string for a nested join. Is this something you would be interested in seeing a PR for?
