### ISSUE TITLE
HAVING support

### ISSUE THREAD

**Issue by gyllen** [hiddentao/squel#86]
As being described in postgresql documentation here.

http://www.postgresql.org/docs/9.1/static/tutorial-agg.html

**Comment by hiddentao** [comment]
Am closing this for now until future interest determines a re-opening.

**Comment by banzai-samurai** [comment]
+1 for this feature

**Comment by kamote** [comment]
is there any workaround to make this work?

**Comment by hiddentao** [comment]
Squel is designed to be extensible, so you can implement a `HAVING` block yourself and redefine the Select query builder accordingly, e.g. http://hiddentao.github.io/squel/#custom_queries

**Comment by sergiofilhowz** [comment]
Just commited a simple implementation of this feature, hope to see this featured in the next version.
