### ISSUE TITLE
How to teach squel to auto escape single quote `'` if value type is string?

### ISSUE THREAD

**Issue by kenvunz** [hiddentao/squel#88]
Hi,

Currently, squel doesn't escape the single quote `'` for value field in `.set` and `.setFields` method, e.g

```
> require('squel').update().table('users').set('value', "I'll").toString()
< "UPDATE users SET value = 'I'll'"
```

Which will cause a statement error from WebSQL

> could not prepare statement (1 near "ll": syntax error)

Is there anyway to make squel automatically escape single quote?

Cheers
Ken

**Comment by ansarisufiyan777** [comment]
```
var q = squel.insert({ replaceSingleQuotes: true })
    .into("postdb.post")
    .set("post_desc", req.body.post_desc)
```

Works Thanks
