### ISSUE TITLE
Use function in a SET

### ISSUE THREAD

**Issue by lahabana** [hiddentao/squel#94]
Is there a way to use a mysql function to set a parameter.
For example I'd like to do something like:
var query = squel.insert().into("news")
						.set("title", title)
						.set("intro", intro)
						.set("body", JSON.stringify(body))
						.set("creation_date", "NOW()");
Quite logically currently NOW() is quoted.

**Comment by hiddentao** [comment]
I'm thinking of something called `squel.param()` - a function which allows you to specify a "complex" parameter value. It would work like this:

```js
squel.update()
 .table("students")
 .set("time", squel.param('GETDATE(?)', '2014' ) )
);
```

toString:

```js
"UPDATE students SET time = (GETDATE('2014'))"
```

toParam:

```js
{
  text: "UPDATE students SET time = (GETDATE(?))",
  values: ['2014']
}
```
